/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = BulkSyncIngestionStatus.Builder.class)
public final class BulkSyncIngestionStatus {
    private final Optional<Boolean> enabled;

    private final Optional<String> highwaterMark;

    private final Optional<Boolean> isRunning;

    private final Optional<String> position;

    private final Optional<OffsetDateTime> positionTime;

    private final Optional<IngestionStatusLevel> status;

    private final Optional<String> statusMessage;

    private final Optional<OffsetDateTime> updatedAt;

    private final Map<String, Object> additionalProperties;

    private BulkSyncIngestionStatus(
            Optional<Boolean> enabled,
            Optional<String> highwaterMark,
            Optional<Boolean> isRunning,
            Optional<String> position,
            Optional<OffsetDateTime> positionTime,
            Optional<IngestionStatusLevel> status,
            Optional<String> statusMessage,
            Optional<OffsetDateTime> updatedAt,
            Map<String, Object> additionalProperties) {
        this.enabled = enabled;
        this.highwaterMark = highwaterMark;
        this.isRunning = isRunning;
        this.position = position;
        this.positionTime = positionTime;
        this.status = status;
        this.statusMessage = statusMessage;
        this.updatedAt = updatedAt;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("enabled")
    public Optional<Boolean> getEnabled() {
        return enabled;
    }

    @JsonProperty("highwater_mark")
    public Optional<String> getHighwaterMark() {
        return highwaterMark;
    }

    @JsonProperty("is_running")
    public Optional<Boolean> getIsRunning() {
        return isRunning;
    }

    @JsonProperty("position")
    public Optional<String> getPosition() {
        return position;
    }

    @JsonProperty("position_time")
    public Optional<OffsetDateTime> getPositionTime() {
        return positionTime;
    }

    @JsonProperty("status")
    public Optional<IngestionStatusLevel> getStatus() {
        return status;
    }

    @JsonProperty("status_message")
    public Optional<String> getStatusMessage() {
        return statusMessage;
    }

    @JsonProperty("updated_at")
    public Optional<OffsetDateTime> getUpdatedAt() {
        return updatedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BulkSyncIngestionStatus && equalTo((BulkSyncIngestionStatus) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BulkSyncIngestionStatus other) {
        return enabled.equals(other.enabled)
                && highwaterMark.equals(other.highwaterMark)
                && isRunning.equals(other.isRunning)
                && position.equals(other.position)
                && positionTime.equals(other.positionTime)
                && status.equals(other.status)
                && statusMessage.equals(other.statusMessage)
                && updatedAt.equals(other.updatedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.enabled,
                this.highwaterMark,
                this.isRunning,
                this.position,
                this.positionTime,
                this.status,
                this.statusMessage,
                this.updatedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> enabled = Optional.empty();

        private Optional<String> highwaterMark = Optional.empty();

        private Optional<Boolean> isRunning = Optional.empty();

        private Optional<String> position = Optional.empty();

        private Optional<OffsetDateTime> positionTime = Optional.empty();

        private Optional<IngestionStatusLevel> status = Optional.empty();

        private Optional<String> statusMessage = Optional.empty();

        private Optional<OffsetDateTime> updatedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BulkSyncIngestionStatus other) {
            enabled(other.getEnabled());
            highwaterMark(other.getHighwaterMark());
            isRunning(other.getIsRunning());
            position(other.getPosition());
            positionTime(other.getPositionTime());
            status(other.getStatus());
            statusMessage(other.getStatusMessage());
            updatedAt(other.getUpdatedAt());
            return this;
        }

        @JsonSetter(value = "enabled", nulls = Nulls.SKIP)
        public Builder enabled(Optional<Boolean> enabled) {
            this.enabled = enabled;
            return this;
        }

        public Builder enabled(Boolean enabled) {
            this.enabled = Optional.of(enabled);
            return this;
        }

        @JsonSetter(value = "highwater_mark", nulls = Nulls.SKIP)
        public Builder highwaterMark(Optional<String> highwaterMark) {
            this.highwaterMark = highwaterMark;
            return this;
        }

        public Builder highwaterMark(String highwaterMark) {
            this.highwaterMark = Optional.of(highwaterMark);
            return this;
        }

        @JsonSetter(value = "is_running", nulls = Nulls.SKIP)
        public Builder isRunning(Optional<Boolean> isRunning) {
            this.isRunning = isRunning;
            return this;
        }

        public Builder isRunning(Boolean isRunning) {
            this.isRunning = Optional.of(isRunning);
            return this;
        }

        @JsonSetter(value = "position", nulls = Nulls.SKIP)
        public Builder position(Optional<String> position) {
            this.position = position;
            return this;
        }

        public Builder position(String position) {
            this.position = Optional.of(position);
            return this;
        }

        @JsonSetter(value = "position_time", nulls = Nulls.SKIP)
        public Builder positionTime(Optional<OffsetDateTime> positionTime) {
            this.positionTime = positionTime;
            return this;
        }

        public Builder positionTime(OffsetDateTime positionTime) {
            this.positionTime = Optional.of(positionTime);
            return this;
        }

        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public Builder status(Optional<IngestionStatusLevel> status) {
            this.status = status;
            return this;
        }

        public Builder status(IngestionStatusLevel status) {
            this.status = Optional.of(status);
            return this;
        }

        @JsonSetter(value = "status_message", nulls = Nulls.SKIP)
        public Builder statusMessage(Optional<String> statusMessage) {
            this.statusMessage = statusMessage;
            return this;
        }

        public Builder statusMessage(String statusMessage) {
            this.statusMessage = Optional.of(statusMessage);
            return this;
        }

        @JsonSetter(value = "updated_at", nulls = Nulls.SKIP)
        public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Builder updatedAt(OffsetDateTime updatedAt) {
            this.updatedAt = Optional.of(updatedAt);
            return this;
        }

        public BulkSyncIngestionStatus build() {
            return new BulkSyncIngestionStatus(
                    enabled,
                    highwaterMark,
                    isRunning,
                    position,
                    positionTime,
                    status,
                    statusMessage,
                    updatedAt,
                    additionalProperties);
        }
    }
}
