/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_EMPTY)
@JsonDeserialize(builder = BulkBulkSyncSchedule.Builder.class)
public final class BulkBulkSyncSchedule {
    private final Optional<OffsetDateTime> createdAt;

    private final Optional<String> createdBy;

    private final Optional<String> dayOfMonth;

    private final Optional<String> dayOfWeek;

    private final Optional<OffsetDateTime> deletedAt;

    private final Optional<String> deletedBy;

    private final ScheduleFrequency frequency;

    private final Optional<String> hour;

    private final Optional<String> minute;

    private final Optional<String> month;

    private final Optional<BulkSelectiveMode> selectiveMode;

    private final Optional<String> syncId;

    private final Optional<OffsetDateTime> updatedAt;

    private final Optional<String> updatedBy;

    private final Map<String, Object> additionalProperties;

    private BulkBulkSyncSchedule(
            Optional<OffsetDateTime> createdAt,
            Optional<String> createdBy,
            Optional<String> dayOfMonth,
            Optional<String> dayOfWeek,
            Optional<OffsetDateTime> deletedAt,
            Optional<String> deletedBy,
            ScheduleFrequency frequency,
            Optional<String> hour,
            Optional<String> minute,
            Optional<String> month,
            Optional<BulkSelectiveMode> selectiveMode,
            Optional<String> syncId,
            Optional<OffsetDateTime> updatedAt,
            Optional<String> updatedBy,
            Map<String, Object> additionalProperties) {
        this.createdAt = createdAt;
        this.createdBy = createdBy;
        this.dayOfMonth = dayOfMonth;
        this.dayOfWeek = dayOfWeek;
        this.deletedAt = deletedAt;
        this.deletedBy = deletedBy;
        this.frequency = frequency;
        this.hour = hour;
        this.minute = minute;
        this.month = month;
        this.selectiveMode = selectiveMode;
        this.syncId = syncId;
        this.updatedAt = updatedAt;
        this.updatedBy = updatedBy;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("createdAt")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("createdBy")
    public Optional<String> getCreatedBy() {
        return createdBy;
    }

    @JsonProperty("dayOfMonth")
    public Optional<String> getDayOfMonth() {
        return dayOfMonth;
    }

    @JsonProperty("dayOfWeek")
    public Optional<String> getDayOfWeek() {
        return dayOfWeek;
    }

    @JsonProperty("deletedAt")
    public Optional<OffsetDateTime> getDeletedAt() {
        return deletedAt;
    }

    @JsonProperty("deletedBy")
    public Optional<String> getDeletedBy() {
        return deletedBy;
    }

    @JsonProperty("frequency")
    public ScheduleFrequency getFrequency() {
        return frequency;
    }

    @JsonProperty("hour")
    public Optional<String> getHour() {
        return hour;
    }

    @JsonProperty("minute")
    public Optional<String> getMinute() {
        return minute;
    }

    @JsonProperty("month")
    public Optional<String> getMonth() {
        return month;
    }

    @JsonProperty("selectiveMode")
    public Optional<BulkSelectiveMode> getSelectiveMode() {
        return selectiveMode;
    }

    @JsonProperty("syncId")
    public Optional<String> getSyncId() {
        return syncId;
    }

    @JsonProperty("updatedAt")
    public Optional<OffsetDateTime> getUpdatedAt() {
        return updatedAt;
    }

    @JsonProperty("updatedBy")
    public Optional<String> getUpdatedBy() {
        return updatedBy;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BulkBulkSyncSchedule && equalTo((BulkBulkSyncSchedule) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BulkBulkSyncSchedule other) {
        return createdAt.equals(other.createdAt)
                && createdBy.equals(other.createdBy)
                && dayOfMonth.equals(other.dayOfMonth)
                && dayOfWeek.equals(other.dayOfWeek)
                && deletedAt.equals(other.deletedAt)
                && deletedBy.equals(other.deletedBy)
                && frequency.equals(other.frequency)
                && hour.equals(other.hour)
                && minute.equals(other.minute)
                && month.equals(other.month)
                && selectiveMode.equals(other.selectiveMode)
                && syncId.equals(other.syncId)
                && updatedAt.equals(other.updatedAt)
                && updatedBy.equals(other.updatedBy);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.createdAt,
                this.createdBy,
                this.dayOfMonth,
                this.dayOfWeek,
                this.deletedAt,
                this.deletedBy,
                this.frequency,
                this.hour,
                this.minute,
                this.month,
                this.selectiveMode,
                this.syncId,
                this.updatedAt,
                this.updatedBy);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static FrequencyStage builder() {
        return new Builder();
    }

    public interface FrequencyStage {
        _FinalStage frequency(ScheduleFrequency frequency);

        Builder from(BulkBulkSyncSchedule other);
    }

    public interface _FinalStage {
        BulkBulkSyncSchedule build();

        _FinalStage createdAt(Optional<OffsetDateTime> createdAt);

        _FinalStage createdAt(OffsetDateTime createdAt);

        _FinalStage createdBy(Optional<String> createdBy);

        _FinalStage createdBy(String createdBy);

        _FinalStage dayOfMonth(Optional<String> dayOfMonth);

        _FinalStage dayOfMonth(String dayOfMonth);

        _FinalStage dayOfWeek(Optional<String> dayOfWeek);

        _FinalStage dayOfWeek(String dayOfWeek);

        _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt);

        _FinalStage deletedAt(OffsetDateTime deletedAt);

        _FinalStage deletedBy(Optional<String> deletedBy);

        _FinalStage deletedBy(String deletedBy);

        _FinalStage hour(Optional<String> hour);

        _FinalStage hour(String hour);

        _FinalStage minute(Optional<String> minute);

        _FinalStage minute(String minute);

        _FinalStage month(Optional<String> month);

        _FinalStage month(String month);

        _FinalStage selectiveMode(Optional<BulkSelectiveMode> selectiveMode);

        _FinalStage selectiveMode(BulkSelectiveMode selectiveMode);

        _FinalStage syncId(Optional<String> syncId);

        _FinalStage syncId(String syncId);

        _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt);

        _FinalStage updatedAt(OffsetDateTime updatedAt);

        _FinalStage updatedBy(Optional<String> updatedBy);

        _FinalStage updatedBy(String updatedBy);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements FrequencyStage, _FinalStage {
        private ScheduleFrequency frequency;

        private Optional<String> updatedBy = Optional.empty();

        private Optional<OffsetDateTime> updatedAt = Optional.empty();

        private Optional<String> syncId = Optional.empty();

        private Optional<BulkSelectiveMode> selectiveMode = Optional.empty();

        private Optional<String> month = Optional.empty();

        private Optional<String> minute = Optional.empty();

        private Optional<String> hour = Optional.empty();

        private Optional<String> deletedBy = Optional.empty();

        private Optional<OffsetDateTime> deletedAt = Optional.empty();

        private Optional<String> dayOfWeek = Optional.empty();

        private Optional<String> dayOfMonth = Optional.empty();

        private Optional<String> createdBy = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BulkBulkSyncSchedule other) {
            createdAt(other.getCreatedAt());
            createdBy(other.getCreatedBy());
            dayOfMonth(other.getDayOfMonth());
            dayOfWeek(other.getDayOfWeek());
            deletedAt(other.getDeletedAt());
            deletedBy(other.getDeletedBy());
            frequency(other.getFrequency());
            hour(other.getHour());
            minute(other.getMinute());
            month(other.getMonth());
            selectiveMode(other.getSelectiveMode());
            syncId(other.getSyncId());
            updatedAt(other.getUpdatedAt());
            updatedBy(other.getUpdatedBy());
            return this;
        }

        @java.lang.Override
        @JsonSetter("frequency")
        public _FinalStage frequency(ScheduleFrequency frequency) {
            this.frequency = frequency;
            return this;
        }

        @java.lang.Override
        public _FinalStage updatedBy(String updatedBy) {
            this.updatedBy = Optional.of(updatedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "updatedBy", nulls = Nulls.SKIP)
        public _FinalStage updatedBy(Optional<String> updatedBy) {
            this.updatedBy = updatedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage updatedAt(OffsetDateTime updatedAt) {
            this.updatedAt = Optional.of(updatedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "updatedAt", nulls = Nulls.SKIP)
        public _FinalStage updatedAt(Optional<OffsetDateTime> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage syncId(String syncId) {
            this.syncId = Optional.of(syncId);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "syncId", nulls = Nulls.SKIP)
        public _FinalStage syncId(Optional<String> syncId) {
            this.syncId = syncId;
            return this;
        }

        @java.lang.Override
        public _FinalStage selectiveMode(BulkSelectiveMode selectiveMode) {
            this.selectiveMode = Optional.of(selectiveMode);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "selectiveMode", nulls = Nulls.SKIP)
        public _FinalStage selectiveMode(Optional<BulkSelectiveMode> selectiveMode) {
            this.selectiveMode = selectiveMode;
            return this;
        }

        @java.lang.Override
        public _FinalStage month(String month) {
            this.month = Optional.of(month);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "month", nulls = Nulls.SKIP)
        public _FinalStage month(Optional<String> month) {
            this.month = month;
            return this;
        }

        @java.lang.Override
        public _FinalStage minute(String minute) {
            this.minute = Optional.of(minute);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "minute", nulls = Nulls.SKIP)
        public _FinalStage minute(Optional<String> minute) {
            this.minute = minute;
            return this;
        }

        @java.lang.Override
        public _FinalStage hour(String hour) {
            this.hour = Optional.of(hour);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "hour", nulls = Nulls.SKIP)
        public _FinalStage hour(Optional<String> hour) {
            this.hour = hour;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedBy(String deletedBy) {
            this.deletedBy = Optional.of(deletedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedBy", nulls = Nulls.SKIP)
        public _FinalStage deletedBy(Optional<String> deletedBy) {
            this.deletedBy = deletedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage deletedAt(OffsetDateTime deletedAt) {
            this.deletedAt = Optional.of(deletedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "deletedAt", nulls = Nulls.SKIP)
        public _FinalStage deletedAt(Optional<OffsetDateTime> deletedAt) {
            this.deletedAt = deletedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage dayOfWeek(String dayOfWeek) {
            this.dayOfWeek = Optional.of(dayOfWeek);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "dayOfWeek", nulls = Nulls.SKIP)
        public _FinalStage dayOfWeek(Optional<String> dayOfWeek) {
            this.dayOfWeek = dayOfWeek;
            return this;
        }

        @java.lang.Override
        public _FinalStage dayOfMonth(String dayOfMonth) {
            this.dayOfMonth = Optional.of(dayOfMonth);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "dayOfMonth", nulls = Nulls.SKIP)
        public _FinalStage dayOfMonth(Optional<String> dayOfMonth) {
            this.dayOfMonth = dayOfMonth;
            return this;
        }

        @java.lang.Override
        public _FinalStage createdBy(String createdBy) {
            this.createdBy = Optional.of(createdBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "createdBy", nulls = Nulls.SKIP)
        public _FinalStage createdBy(Optional<String> createdBy) {
            this.createdBy = createdBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.of(createdAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "createdAt", nulls = Nulls.SKIP)
        public _FinalStage createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        @java.lang.Override
        public BulkBulkSyncSchedule build() {
            return new BulkBulkSyncSchedule(
                    createdAt,
                    createdBy,
                    dayOfMonth,
                    dayOfWeek,
                    deletedAt,
                    deletedBy,
                    frequency,
                    hour,
                    minute,
                    month,
                    selectiveMode,
                    syncId,
                    updatedAt,
                    updatedBy,
                    additionalProperties);
        }
    }
}
