/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ConnectionUsageSyncStats.Builder.class)
public final class ConnectionUsageSyncStats {
    private final Optional<List<ConnectionUsageCategoryStats>> categories;

    private final Optional<OffsetDateTime> lastRunAt;

    private final Optional<String> syncId;

    private final Optional<String> syncName;

    private final Optional<String> syncType;

    private final Optional<Integer> totalCalls;

    private final Map<String, Object> additionalProperties;

    private ConnectionUsageSyncStats(
            Optional<List<ConnectionUsageCategoryStats>> categories,
            Optional<OffsetDateTime> lastRunAt,
            Optional<String> syncId,
            Optional<String> syncName,
            Optional<String> syncType,
            Optional<Integer> totalCalls,
            Map<String, Object> additionalProperties) {
        this.categories = categories;
        this.lastRunAt = lastRunAt;
        this.syncId = syncId;
        this.syncName = syncName;
        this.syncType = syncType;
        this.totalCalls = totalCalls;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Per-category breakdown of the sync's calls, sorted by calls descending.
     */
    @JsonProperty("categories")
    public Optional<List<ConnectionUsageCategoryStats>> getCategories() {
        return categories;
    }

    /**
     * @return Start time of the sync's most recent execution, or null if it has never run.
     */
    @JsonProperty("lastRunAt")
    public Optional<OffsetDateTime> getLastRunAt() {
        return lastRunAt;
    }

    /**
     * @return Unique identifier of the sync that spent the calls.
     */
    @JsonProperty("syncId")
    public Optional<String> getSyncId() {
        return syncId;
    }

    /**
     * @return Human-readable name of the sync, or empty if it could not be resolved.
     */
    @JsonProperty("syncName")
    public Optional<String> getSyncName() {
        return syncName;
    }

    /**
     * @return Kind of sync that spent the calls (model or bulk).
     */
    @JsonProperty("syncType")
    public Optional<String> getSyncType() {
        return syncType;
    }

    /**
     * @return Total API calls the sync spent against this connection in the last 24 hours.
     */
    @JsonProperty("totalCalls")
    public Optional<Integer> getTotalCalls() {
        return totalCalls;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectionUsageSyncStats && equalTo((ConnectionUsageSyncStats) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ConnectionUsageSyncStats other) {
        return categories.equals(other.categories)
                && lastRunAt.equals(other.lastRunAt)
                && syncId.equals(other.syncId)
                && syncName.equals(other.syncName)
                && syncType.equals(other.syncType)
                && totalCalls.equals(other.totalCalls);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.categories, this.lastRunAt, this.syncId, this.syncName, this.syncType, this.totalCalls);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ConnectionUsageCategoryStats>> categories = Optional.empty();

        private Optional<OffsetDateTime> lastRunAt = Optional.empty();

        private Optional<String> syncId = Optional.empty();

        private Optional<String> syncName = Optional.empty();

        private Optional<String> syncType = Optional.empty();

        private Optional<Integer> totalCalls = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ConnectionUsageSyncStats other) {
            categories(other.getCategories());
            lastRunAt(other.getLastRunAt());
            syncId(other.getSyncId());
            syncName(other.getSyncName());
            syncType(other.getSyncType());
            totalCalls(other.getTotalCalls());
            return this;
        }

        /**
         * <p>Per-category breakdown of the sync's calls, sorted by calls descending.</p>
         */
        @JsonSetter(value = "categories", nulls = Nulls.SKIP)
        public Builder categories(Optional<List<ConnectionUsageCategoryStats>> categories) {
            this.categories = categories;
            return this;
        }

        public Builder categories(List<ConnectionUsageCategoryStats> categories) {
            this.categories = Optional.ofNullable(categories);
            return this;
        }

        /**
         * <p>Start time of the sync's most recent execution, or null if it has never run.</p>
         */
        @JsonSetter(value = "lastRunAt", nulls = Nulls.SKIP)
        public Builder lastRunAt(Optional<OffsetDateTime> lastRunAt) {
            this.lastRunAt = lastRunAt;
            return this;
        }

        public Builder lastRunAt(OffsetDateTime lastRunAt) {
            this.lastRunAt = Optional.ofNullable(lastRunAt);
            return this;
        }

        /**
         * <p>Unique identifier of the sync that spent the calls.</p>
         */
        @JsonSetter(value = "syncId", nulls = Nulls.SKIP)
        public Builder syncId(Optional<String> syncId) {
            this.syncId = syncId;
            return this;
        }

        public Builder syncId(String syncId) {
            this.syncId = Optional.ofNullable(syncId);
            return this;
        }

        /**
         * <p>Human-readable name of the sync, or empty if it could not be resolved.</p>
         */
        @JsonSetter(value = "syncName", nulls = Nulls.SKIP)
        public Builder syncName(Optional<String> syncName) {
            this.syncName = syncName;
            return this;
        }

        public Builder syncName(String syncName) {
            this.syncName = Optional.ofNullable(syncName);
            return this;
        }

        /**
         * <p>Kind of sync that spent the calls (model or bulk).</p>
         */
        @JsonSetter(value = "syncType", nulls = Nulls.SKIP)
        public Builder syncType(Optional<String> syncType) {
            this.syncType = syncType;
            return this;
        }

        public Builder syncType(String syncType) {
            this.syncType = Optional.ofNullable(syncType);
            return this;
        }

        /**
         * <p>Total API calls the sync spent against this connection in the last 24 hours.</p>
         */
        @JsonSetter(value = "totalCalls", nulls = Nulls.SKIP)
        public Builder totalCalls(Optional<Integer> totalCalls) {
            this.totalCalls = totalCalls;
            return this;
        }

        public Builder totalCalls(Integer totalCalls) {
            this.totalCalls = Optional.ofNullable(totalCalls);
            return this;
        }

        public ConnectionUsageSyncStats build() {
            return new ConnectionUsageSyncStats(
                    categories, lastRunAt, syncId, syncName, syncType, totalCalls, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
