/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.core.JsonParseException;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.polytomic.api.core.ObjectMappers;
import java.io.IOException;
import java.util.Objects;

@JsonDeserialize(using = EventPayload.Deserializer.class)
public final class EventPayload {
    private final Object value;

    private final int type;

    private EventPayload(Object value, int type) {
        this.value = value;
        this.type = type;
    }

    @JsonValue
    public Object get() {
        return this.value;
    }

    @SuppressWarnings("unchecked")
    public <T> T visit(Visitor<T> visitor) {
        if (this.type == 0) {
            return visitor.visit((EventingSyncRunningEvent) this.value);
        } else if (this.type == 1) {
            return visitor.visit((EventingSyncCompletedEvent) this.value);
        } else if (this.type == 2) {
            return visitor.visit((EventingSyncFailedEvent) this.value);
        } else if (this.type == 3) {
            return visitor.visit((EventingSyncCanceledEvent) this.value);
        } else if (this.type == 4) {
            return visitor.visit((EventingSyncCompletedWithErrorsEvent) this.value);
        } else if (this.type == 5) {
            return visitor.visit((EventingBulkSyncRunningEvent) this.value);
        } else if (this.type == 6) {
            return visitor.visit((EventingBulkSyncCompletedEvent) this.value);
        } else if (this.type == 7) {
            return visitor.visit((EventingBulkSyncCanceledEvent) this.value);
        } else if (this.type == 8) {
            return visitor.visit((EventingBulkSyncCompletedWithErrorEvent) this.value);
        } else if (this.type == 9) {
            return visitor.visit((EventingBulkSyncFailedEvent) this.value);
        }
        throw new IllegalStateException("Failed to visit value. This should never happen.");
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventPayload && equalTo((EventPayload) other);
    }

    private boolean equalTo(EventPayload other) {
        return value.equals(other.value);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.value);
    }

    @java.lang.Override
    public String toString() {
        return this.value.toString();
    }

    public static EventPayload of(EventingSyncRunningEvent value) {
        return new EventPayload(value, 0);
    }

    public static EventPayload of(EventingSyncCompletedEvent value) {
        return new EventPayload(value, 1);
    }

    public static EventPayload of(EventingSyncFailedEvent value) {
        return new EventPayload(value, 2);
    }

    public static EventPayload of(EventingSyncCanceledEvent value) {
        return new EventPayload(value, 3);
    }

    public static EventPayload of(EventingSyncCompletedWithErrorsEvent value) {
        return new EventPayload(value, 4);
    }

    public static EventPayload of(EventingBulkSyncRunningEvent value) {
        return new EventPayload(value, 5);
    }

    public static EventPayload of(EventingBulkSyncCompletedEvent value) {
        return new EventPayload(value, 6);
    }

    public static EventPayload of(EventingBulkSyncCanceledEvent value) {
        return new EventPayload(value, 7);
    }

    public static EventPayload of(EventingBulkSyncCompletedWithErrorEvent value) {
        return new EventPayload(value, 8);
    }

    public static EventPayload of(EventingBulkSyncFailedEvent value) {
        return new EventPayload(value, 9);
    }

    public interface Visitor<T> {
        T visit(EventingSyncRunningEvent value);

        T visit(EventingSyncCompletedEvent value);

        T visit(EventingSyncFailedEvent value);

        T visit(EventingSyncCanceledEvent value);

        T visit(EventingSyncCompletedWithErrorsEvent value);

        T visit(EventingBulkSyncRunningEvent value);

        T visit(EventingBulkSyncCompletedEvent value);

        T visit(EventingBulkSyncCanceledEvent value);

        T visit(EventingBulkSyncCompletedWithErrorEvent value);

        T visit(EventingBulkSyncFailedEvent value);
    }

    static final class Deserializer extends StdDeserializer<EventPayload> {
        Deserializer() {
            super(EventPayload.class);
        }

        @java.lang.Override
        public EventPayload deserialize(JsonParser p, DeserializationContext context) throws IOException {
            Object value = p.readValueAs(Object.class);
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingSyncRunningEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingSyncCompletedEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingSyncFailedEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingSyncCanceledEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingSyncCompletedWithErrorsEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingBulkSyncRunningEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingBulkSyncCompletedEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingBulkSyncCanceledEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingBulkSyncCompletedWithErrorEvent.class));
            } catch (RuntimeException e) {
            }
            try {
                return of(ObjectMappers.JSON_MAPPER.convertValue(value, EventingBulkSyncFailedEvent.class));
            } catch (RuntimeException e) {
            }
            throw new JsonParseException(p, "Failed to deserialize");
        }
    }
}
