/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonValue;

public enum ExecutionStatus {
    CREATED("created"),

    SCHEDULED("scheduled"),

    QUEUED("queued"),

    WAITING("waiting"),

    RUNNING("running"),

    PROCESSING("processing"),

    CANCELING("canceling"),

    CANCELED("canceled"),

    COMPLETED("completed"),

    FAILED("failed"),

    INTERRUPTED("interrupted");

    private final String value;

    ExecutionStatus(String value) {
        this.value = value;
    }

    @JsonValue
    @java.lang.Override
    public String toString() {
        return this.value;
    }
}
