/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ExecutionConsoleLogsResponse.Builder.class)
public final class ExecutionConsoleLogsResponse {
    private final Optional<List<ExecutionConsoleLogEntry>> entries;

    private final Optional<String> nextCursor;

    private final Map<String, Object> additionalProperties;

    private ExecutionConsoleLogsResponse(
            Optional<List<ExecutionConsoleLogEntry>> entries,
            Optional<String> nextCursor,
            Map<String, Object> additionalProperties) {
        this.entries = entries;
        this.nextCursor = nextCursor;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("entries")
    public Optional<List<ExecutionConsoleLogEntry>> getEntries() {
        return entries;
    }

    @JsonProperty("next_cursor")
    public Optional<String> getNextCursor() {
        return nextCursor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ExecutionConsoleLogsResponse && equalTo((ExecutionConsoleLogsResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ExecutionConsoleLogsResponse other) {
        return entries.equals(other.entries) && nextCursor.equals(other.nextCursor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.entries, this.nextCursor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<ExecutionConsoleLogEntry>> entries = Optional.empty();

        private Optional<String> nextCursor = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ExecutionConsoleLogsResponse other) {
            entries(other.getEntries());
            nextCursor(other.getNextCursor());
            return this;
        }

        @JsonSetter(value = "entries", nulls = Nulls.SKIP)
        public Builder entries(Optional<List<ExecutionConsoleLogEntry>> entries) {
            this.entries = entries;
            return this;
        }

        public Builder entries(List<ExecutionConsoleLogEntry> entries) {
            this.entries = Optional.ofNullable(entries);
            return this;
        }

        @JsonSetter(value = "next_cursor", nulls = Nulls.SKIP)
        public Builder nextCursor(Optional<String> nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        public Builder nextCursor(String nextCursor) {
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        public ExecutionConsoleLogsResponse build() {
            return new ExecutionConsoleLogsResponse(entries, nextCursor, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
