/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HarborContextResponse.Builder.class)
public final class HarborContextResponse {
    private final Optional<String> content;

    private final Optional<OffsetDateTime> createdAt;

    private final Optional<String> description;

    private final Optional<String> id;

    private final Optional<String> revisionId;

    private final Optional<String> title;

    private final Optional<OffsetDateTime> updatedAt;

    private final Optional<Integer> version;

    private final Map<String, Object> additionalProperties;

    private HarborContextResponse(
            Optional<String> content,
            Optional<OffsetDateTime> createdAt,
            Optional<String> description,
            Optional<String> id,
            Optional<String> revisionId,
            Optional<String> title,
            Optional<OffsetDateTime> updatedAt,
            Optional<Integer> version,
            Map<String, Object> additionalProperties) {
        this.content = content;
        this.createdAt = createdAt;
        this.description = description;
        this.id = id;
        this.revisionId = revisionId;
        this.title = title;
        this.updatedAt = updatedAt;
        this.version = version;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Complete plain-text context content.
     */
    @JsonProperty("content")
    public Optional<String> getContent() {
        return content;
    }

    /**
     * @return When the context document was created.
     */
    @JsonProperty("created_at")
    public Optional<OffsetDateTime> getCreatedAt() {
        return createdAt;
    }

    /**
     * @return Short summary of the context document.
     */
    @JsonProperty("description")
    public Optional<String> getDescription() {
        return description;
    }

    /**
     * @return Unique identifier of the context document.
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return Exact immutable revision currently published for this context document.
     */
    @JsonProperty("revision_id")
    public Optional<String> getRevisionId() {
        return revisionId;
    }

    /**
     * @return Human-readable context title.
     */
    @JsonProperty("title")
    public Optional<String> getTitle() {
        return title;
    }

    /**
     * @return When the context document was last updated.
     */
    @JsonProperty("updated_at")
    public Optional<OffsetDateTime> getUpdatedAt() {
        return updatedAt;
    }

    /**
     * @return Current published version number of the context document.
     */
    @JsonProperty("version")
    public Optional<Integer> getVersion() {
        return version;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HarborContextResponse && equalTo((HarborContextResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HarborContextResponse other) {
        return content.equals(other.content)
                && createdAt.equals(other.createdAt)
                && description.equals(other.description)
                && id.equals(other.id)
                && revisionId.equals(other.revisionId)
                && title.equals(other.title)
                && updatedAt.equals(other.updatedAt)
                && version.equals(other.version);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.content,
                this.createdAt,
                this.description,
                this.id,
                this.revisionId,
                this.title,
                this.updatedAt,
                this.version);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> content = Optional.empty();

        private Optional<OffsetDateTime> createdAt = Optional.empty();

        private Optional<String> description = Optional.empty();

        private Optional<String> id = Optional.empty();

        private Optional<String> revisionId = Optional.empty();

        private Optional<String> title = Optional.empty();

        private Optional<OffsetDateTime> updatedAt = Optional.empty();

        private Optional<Integer> version = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(HarborContextResponse other) {
            content(other.getContent());
            createdAt(other.getCreatedAt());
            description(other.getDescription());
            id(other.getId());
            revisionId(other.getRevisionId());
            title(other.getTitle());
            updatedAt(other.getUpdatedAt());
            version(other.getVersion());
            return this;
        }

        /**
         * <p>Complete plain-text context content.</p>
         */
        @JsonSetter(value = "content", nulls = Nulls.SKIP)
        public Builder content(Optional<String> content) {
            this.content = content;
            return this;
        }

        public Builder content(String content) {
            this.content = Optional.ofNullable(content);
            return this;
        }

        /**
         * <p>When the context document was created.</p>
         */
        @JsonSetter(value = "created_at", nulls = Nulls.SKIP)
        public Builder createdAt(Optional<OffsetDateTime> createdAt) {
            this.createdAt = createdAt;
            return this;
        }

        public Builder createdAt(OffsetDateTime createdAt) {
            this.createdAt = Optional.ofNullable(createdAt);
            return this;
        }

        /**
         * <p>Short summary of the context document.</p>
         */
        @JsonSetter(value = "description", nulls = Nulls.SKIP)
        public Builder description(Optional<String> description) {
            this.description = description;
            return this;
        }

        public Builder description(String description) {
            this.description = Optional.ofNullable(description);
            return this;
        }

        /**
         * <p>Unique identifier of the context document.</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Exact immutable revision currently published for this context document.</p>
         */
        @JsonSetter(value = "revision_id", nulls = Nulls.SKIP)
        public Builder revisionId(Optional<String> revisionId) {
            this.revisionId = revisionId;
            return this;
        }

        public Builder revisionId(String revisionId) {
            this.revisionId = Optional.ofNullable(revisionId);
            return this;
        }

        /**
         * <p>Human-readable context title.</p>
         */
        @JsonSetter(value = "title", nulls = Nulls.SKIP)
        public Builder title(Optional<String> title) {
            this.title = title;
            return this;
        }

        public Builder title(String title) {
            this.title = Optional.ofNullable(title);
            return this;
        }

        /**
         * <p>When the context document was last updated.</p>
         */
        @JsonSetter(value = "updated_at", nulls = Nulls.SKIP)
        public Builder updatedAt(Optional<OffsetDateTime> updatedAt) {
            this.updatedAt = updatedAt;
            return this;
        }

        public Builder updatedAt(OffsetDateTime updatedAt) {
            this.updatedAt = Optional.ofNullable(updatedAt);
            return this;
        }

        /**
         * <p>Current published version number of the context document.</p>
         */
        @JsonSetter(value = "version", nulls = Nulls.SKIP)
        public Builder version(Optional<Integer> version) {
            this.version = version;
            return this;
        }

        public Builder version(Integer version) {
            this.version = Optional.ofNullable(version);
            return this;
        }

        public HarborContextResponse build() {
            return new HarborContextResponse(
                    content, createdAt, description, id, revisionId, title, updatedAt, version, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
