/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HarboractivityapiHarborActivityTarget.Builder.class)
public final class HarboractivityapiHarborActivityTarget {
    private final Optional<String> id;

    private final Optional<String> label;

    private final Optional<Boolean> labelTruncated;

    private final Optional<String> type;

    private final Map<String, Object> additionalProperties;

    private HarboractivityapiHarborActivityTarget(
            Optional<String> id,
            Optional<String> label,
            Optional<Boolean> labelTruncated,
            Optional<String> type,
            Map<String, Object> additionalProperties) {
        this.id = id;
        this.label = label;
        this.labelTruncated = labelTruncated;
        this.type = type;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    @JsonProperty("label")
    public Optional<String> getLabel() {
        return label;
    }

    @JsonProperty("label_truncated")
    public Optional<Boolean> getLabelTruncated() {
        return labelTruncated;
    }

    @JsonProperty("type")
    public Optional<String> getType() {
        return type;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HarboractivityapiHarborActivityTarget
                && equalTo((HarboractivityapiHarborActivityTarget) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HarboractivityapiHarborActivityTarget other) {
        return id.equals(other.id)
                && label.equals(other.label)
                && labelTruncated.equals(other.labelTruncated)
                && type.equals(other.type);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.id, this.label, this.labelTruncated, this.type);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> id = Optional.empty();

        private Optional<String> label = Optional.empty();

        private Optional<Boolean> labelTruncated = Optional.empty();

        private Optional<String> type = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(HarboractivityapiHarborActivityTarget other) {
            id(other.getId());
            label(other.getLabel());
            labelTruncated(other.getLabelTruncated());
            type(other.getType());
            return this;
        }

        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        @JsonSetter(value = "label", nulls = Nulls.SKIP)
        public Builder label(Optional<String> label) {
            this.label = label;
            return this;
        }

        public Builder label(String label) {
            this.label = Optional.ofNullable(label);
            return this;
        }

        @JsonSetter(value = "label_truncated", nulls = Nulls.SKIP)
        public Builder labelTruncated(Optional<Boolean> labelTruncated) {
            this.labelTruncated = labelTruncated;
            return this;
        }

        public Builder labelTruncated(Boolean labelTruncated) {
            this.labelTruncated = Optional.ofNullable(labelTruncated);
            return this;
        }

        @JsonSetter(value = "type", nulls = Nulls.SKIP)
        public Builder type(Optional<String> type) {
            this.type = type;
            return this;
        }

        public Builder type(String type) {
            this.type = Optional.ofNullable(type);
            return this;
        }

        public HarboractivityapiHarborActivityTarget build() {
            return new HarboractivityapiHarborActivityTarget(id, label, labelTruncated, type, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
