/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = HarborContextDraftListEnvelope.Builder.class)
public final class HarborContextDraftListEnvelope {
    private final Optional<List<HarborContextDraftMetadataResponse>> data;

    private final Optional<PaginationDetails> pagination;

    private final Map<String, Object> additionalProperties;

    private HarborContextDraftListEnvelope(
            Optional<List<HarborContextDraftMetadataResponse>> data,
            Optional<PaginationDetails> pagination,
            Map<String, Object> additionalProperties) {
        this.data = data;
        this.pagination = pagination;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public Optional<List<HarborContextDraftMetadataResponse>> getData() {
        return data;
    }

    @JsonProperty("pagination")
    public Optional<PaginationDetails> getPagination() {
        return pagination;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof HarborContextDraftListEnvelope && equalTo((HarborContextDraftListEnvelope) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(HarborContextDraftListEnvelope other) {
        return data.equals(other.data) && pagination.equals(other.pagination);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.pagination);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<HarborContextDraftMetadataResponse>> data = Optional.empty();

        private Optional<PaginationDetails> pagination = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(HarborContextDraftListEnvelope other) {
            data(other.getData());
            pagination(other.getPagination());
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(Optional<List<HarborContextDraftMetadataResponse>> data) {
            this.data = data;
            return this;
        }

        public Builder data(List<HarborContextDraftMetadataResponse> data) {
            this.data = Optional.ofNullable(data);
            return this;
        }

        @JsonSetter(value = "pagination", nulls = Nulls.SKIP)
        public Builder pagination(Optional<PaginationDetails> pagination) {
            this.pagination = pagination;
            return this;
        }

        public Builder pagination(PaginationDetails pagination) {
            this.pagination = Optional.ofNullable(pagination);
            return this;
        }

        public HarborContextDraftListEnvelope build() {
            return new HarborContextDraftListEnvelope(data, pagination, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
