/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.types;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = TargetResponse.Builder.class)
public final class TargetResponse {
    private final Optional<List<TargetField>> fields;

    private final Optional<String> id;

    private final Optional<List<Mode>> modes;

    private final Optional<String> name;

    private final Optional<SyncDestinationProperties> properties;

    private final Optional<OffsetDateTime> refreshedAt;

    private final Map<String, Object> additionalProperties;

    private TargetResponse(
            Optional<List<TargetField>> fields,
            Optional<String> id,
            Optional<List<Mode>> modes,
            Optional<String> name,
            Optional<SyncDestinationProperties> properties,
            Optional<OffsetDateTime> refreshedAt,
            Map<String, Object> additionalProperties) {
        this.fields = fields;
        this.id = id;
        this.modes = modes;
        this.name = name;
        this.properties = properties;
        this.refreshedAt = refreshedAt;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Fields available for mapping on this target. Empty for backends where the new target's columns are user-defined (e.g. SQL databases).
     */
    @JsonProperty("fields")
    public Optional<List<TargetField>> getFields() {
        return fields;
    }

    /**
     * @return Backend-specific identifier of the target object. For not-yet-created targets, this is an internal placeholder identifier that callers should not rely on.
     */
    @JsonProperty("id")
    public Optional<String> getId() {
        return id;
    }

    /**
     * @return Sync modes the target supports (e.g. create, update, upsert). The chosen mode determines which operations the sync may perform.
     */
    @JsonProperty("modes")
    public Optional<List<Mode>> getModes() {
        return modes;
    }

    /**
     * @return Human-readable name of the target object.
     */
    @JsonProperty("name")
    public Optional<String> getName() {
        return name;
    }

    @JsonProperty("properties")
    public Optional<SyncDestinationProperties> getProperties() {
        return properties;
    }

    /**
     * @return Timestamp the target's cached schema was last refreshed. Zero for targets that do not have a cached schema (including not-yet-created targets).
     */
    @JsonProperty("refreshed_at")
    public Optional<OffsetDateTime> getRefreshedAt() {
        return refreshedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof TargetResponse && equalTo((TargetResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(TargetResponse other) {
        return fields.equals(other.fields)
                && id.equals(other.id)
                && modes.equals(other.modes)
                && name.equals(other.name)
                && properties.equals(other.properties)
                && refreshedAt.equals(other.refreshedAt);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.fields, this.id, this.modes, this.name, this.properties, this.refreshedAt);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<TargetField>> fields = Optional.empty();

        private Optional<String> id = Optional.empty();

        private Optional<List<Mode>> modes = Optional.empty();

        private Optional<String> name = Optional.empty();

        private Optional<SyncDestinationProperties> properties = Optional.empty();

        private Optional<OffsetDateTime> refreshedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(TargetResponse other) {
            fields(other.getFields());
            id(other.getId());
            modes(other.getModes());
            name(other.getName());
            properties(other.getProperties());
            refreshedAt(other.getRefreshedAt());
            return this;
        }

        /**
         * <p>Fields available for mapping on this target. Empty for backends where the new target's columns are user-defined (e.g. SQL databases).</p>
         */
        @JsonSetter(value = "fields", nulls = Nulls.SKIP)
        public Builder fields(Optional<List<TargetField>> fields) {
            this.fields = fields;
            return this;
        }

        public Builder fields(List<TargetField> fields) {
            this.fields = Optional.ofNullable(fields);
            return this;
        }

        /**
         * <p>Backend-specific identifier of the target object. For not-yet-created targets, this is an internal placeholder identifier that callers should not rely on.</p>
         */
        @JsonSetter(value = "id", nulls = Nulls.SKIP)
        public Builder id(Optional<String> id) {
            this.id = id;
            return this;
        }

        public Builder id(String id) {
            this.id = Optional.ofNullable(id);
            return this;
        }

        /**
         * <p>Sync modes the target supports (e.g. create, update, upsert). The chosen mode determines which operations the sync may perform.</p>
         */
        @JsonSetter(value = "modes", nulls = Nulls.SKIP)
        public Builder modes(Optional<List<Mode>> modes) {
            this.modes = modes;
            return this;
        }

        public Builder modes(List<Mode> modes) {
            this.modes = Optional.ofNullable(modes);
            return this;
        }

        /**
         * <p>Human-readable name of the target object.</p>
         */
        @JsonSetter(value = "name", nulls = Nulls.SKIP)
        public Builder name(Optional<String> name) {
            this.name = name;
            return this;
        }

        public Builder name(String name) {
            this.name = Optional.ofNullable(name);
            return this;
        }

        @JsonSetter(value = "properties", nulls = Nulls.SKIP)
        public Builder properties(Optional<SyncDestinationProperties> properties) {
            this.properties = properties;
            return this;
        }

        public Builder properties(SyncDestinationProperties properties) {
            this.properties = Optional.ofNullable(properties);
            return this;
        }

        /**
         * <p>Timestamp the target's cached schema was last refreshed. Zero for targets that do not have a cached schema (including not-yet-created targets).</p>
         */
        @JsonSetter(value = "refreshed_at", nulls = Nulls.SKIP)
        public Builder refreshedAt(Optional<OffsetDateTime> refreshedAt) {
            this.refreshedAt = refreshedAt;
            return this;
        }

        public Builder refreshedAt(OffsetDateTime refreshedAt) {
            this.refreshedAt = Optional.ofNullable(refreshedAt);
            return this;
        }

        public TargetResponse build() {
            return new TargetResponse(fields, id, modes, name, properties, refreshedAt, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
