/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.entities;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.ObjectMappers;
import com.polytomic.api.core.PolytomicApiException;
import com.polytomic.api.core.PolytomicException;
import com.polytomic.api.core.PolytomicHttpResponse;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.errors.ForbiddenError;
import com.polytomic.api.errors.InternalServerError;
import com.polytomic.api.errors.NotFoundError;
import com.polytomic.api.errors.UnauthorizedError;
import com.polytomic.api.types.ApiError;
import com.polytomic.api.types.EntityResponseEnvelope;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawEntitiesClient {
    protected final ClientOptions clientOptions;

    public RawEntitiesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Returns a resolved entity by ID.
     * <p>Looks up a UUID within the caller's current organization and returns the
     * resource type plus enough context to fetch the canonical resource.</p>
     * <p>This endpoint is useful when you have an execution, sync, model, connection,
     * organization, or user UUID and need to determine what it refers to.</p>
     * <p>The response always includes:</p>
     * <ul>
     * <li><code>id</code>: the UUID that was resolved.</li>
     * <li><code>type</code>: the resolved entity type.</li>
     * <li><code>canonical_path</code>: the canonical REST path for the resolved resource.</li>
     * </ul>
     * <p>The response may also include:</p>
     * <ul>
     * <li><code>relationships</code>: parent resources needed to address nested resources.</li>
     * <li><code>context</code>: lightweight additional context, such as bulk sync <code>schema_ids</code>.</li>
     * </ul>
     * <p>For the normal user-scoped endpoint, <code>organization_id</code> is omitted from the
     * response.</p>
     * <p>Supported <code>type</code> values currently include:</p>
     * <ul>
     * <li><code>organization</code></li>
     * <li><code>user</code></li>
     * <li><code>connection</code></li>
     * <li><code>model</code></li>
     * <li><code>sync</code></li>
     * <li><code>sync_execution</code></li>
     * <li><code>bulk_sync</code></li>
     * <li><code>bulk_sync_execution</code></li>
     * </ul>
     * <p>Examples:</p>
     * <ul>
     * <li>A model sync execution resolves to a <code>sync_execution</code> and includes a <code>sync</code>
     * relationship.</li>
     * <li>A bulk sync execution resolves to a <code>bulk_sync_execution</code>, includes a
     * <code>bulk_sync</code> relationship, and may include <code>context.schema_ids</code>.</li>
     * </ul>
     * <p>If the UUID does not exist, or exists outside the caller's scoped
     * organization, the endpoint returns <code>404</code>.</p>
     */
    public PolytomicHttpResponse<EntityResponseEnvelope> get(String id) {
        return get(id, null);
    }

    /**
     * Returns a resolved entity by ID.
     * <p>Looks up a UUID within the caller's current organization and returns the
     * resource type plus enough context to fetch the canonical resource.</p>
     * <p>This endpoint is useful when you have an execution, sync, model, connection,
     * organization, or user UUID and need to determine what it refers to.</p>
     * <p>The response always includes:</p>
     * <ul>
     * <li><code>id</code>: the UUID that was resolved.</li>
     * <li><code>type</code>: the resolved entity type.</li>
     * <li><code>canonical_path</code>: the canonical REST path for the resolved resource.</li>
     * </ul>
     * <p>The response may also include:</p>
     * <ul>
     * <li><code>relationships</code>: parent resources needed to address nested resources.</li>
     * <li><code>context</code>: lightweight additional context, such as bulk sync <code>schema_ids</code>.</li>
     * </ul>
     * <p>For the normal user-scoped endpoint, <code>organization_id</code> is omitted from the
     * response.</p>
     * <p>Supported <code>type</code> values currently include:</p>
     * <ul>
     * <li><code>organization</code></li>
     * <li><code>user</code></li>
     * <li><code>connection</code></li>
     * <li><code>model</code></li>
     * <li><code>sync</code></li>
     * <li><code>sync_execution</code></li>
     * <li><code>bulk_sync</code></li>
     * <li><code>bulk_sync_execution</code></li>
     * </ul>
     * <p>Examples:</p>
     * <ul>
     * <li>A model sync execution resolves to a <code>sync_execution</code> and includes a <code>sync</code>
     * relationship.</li>
     * <li>A bulk sync execution resolves to a <code>bulk_sync_execution</code>, includes a
     * <code>bulk_sync</code> relationship, and may include <code>context.schema_ids</code>.</li>
     * </ul>
     * <p>If the UUID does not exist, or exists outside the caller's scoped
     * organization, the endpoint returns <code>404</code>.</p>
     */
    public PolytomicHttpResponse<EntityResponseEnvelope> get(String id, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/entities")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PolytomicHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EntityResponseEnvelope.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 401:
                        throw new UnauthorizedError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PolytomicApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PolytomicException("Network error executing HTTP request", e);
        }
    }

    /**
     * Returns a resolved entity by ID within a partner organization scope.
     * <p>Looks up a UUID across organizations using partner authentication and returns
     * the resource type plus enough context to fetch the canonical resource.</p>
     * <p>This endpoint is intended for cross-organization partner workflows where the
     * caller has an arbitrary UUID and needs to discover both the resource type and
     * the organization it belongs to.</p>
     * <p>The response always includes:</p>
     * <ul>
     * <li><code>id</code>: the UUID that was resolved.</li>
     * <li><code>type</code>: the resolved entity type.</li>
     * <li><code>canonical_path</code>: the canonical REST path for the resolved resource.</li>
     * <li><code>organization_id</code>: the organization that owns the resolved resource.</li>
     * </ul>
     * <p>The response may also include:</p>
     * <ul>
     * <li><code>relationships</code>: parent resources needed to address nested resources.</li>
     * <li><code>context</code>: lightweight additional context, such as bulk sync <code>schema_ids</code>.</li>
     * </ul>
     * <p>Supported <code>type</code> values currently include:</p>
     * <ul>
     * <li><code>organization</code></li>
     * <li><code>user</code></li>
     * <li><code>connection</code></li>
     * <li><code>model</code></li>
     * <li><code>sync</code></li>
     * <li><code>sync_execution</code></li>
     * <li><code>bulk_sync</code></li>
     * <li><code>bulk_sync_execution</code></li>
     * </ul>
     * <p>Examples:</p>
     * <ul>
     * <li>A model sync execution resolves to a <code>sync_execution</code> and includes a <code>sync</code>
     * relationship.</li>
     * <li>A bulk sync execution resolves to a <code>bulk_sync_execution</code>, includes a
     * <code>bulk_sync</code> relationship, and may include <code>context.schema_ids</code>.</li>
     * </ul>
     * <p>If the UUID does not exist, the endpoint returns <code>404</code>.</p>
     */
    public PolytomicHttpResponse<EntityResponseEnvelope> getForPartner(String id) {
        return getForPartner(id, null);
    }

    /**
     * Returns a resolved entity by ID within a partner organization scope.
     * <p>Looks up a UUID across organizations using partner authentication and returns
     * the resource type plus enough context to fetch the canonical resource.</p>
     * <p>This endpoint is intended for cross-organization partner workflows where the
     * caller has an arbitrary UUID and needs to discover both the resource type and
     * the organization it belongs to.</p>
     * <p>The response always includes:</p>
     * <ul>
     * <li><code>id</code>: the UUID that was resolved.</li>
     * <li><code>type</code>: the resolved entity type.</li>
     * <li><code>canonical_path</code>: the canonical REST path for the resolved resource.</li>
     * <li><code>organization_id</code>: the organization that owns the resolved resource.</li>
     * </ul>
     * <p>The response may also include:</p>
     * <ul>
     * <li><code>relationships</code>: parent resources needed to address nested resources.</li>
     * <li><code>context</code>: lightweight additional context, such as bulk sync <code>schema_ids</code>.</li>
     * </ul>
     * <p>Supported <code>type</code> values currently include:</p>
     * <ul>
     * <li><code>organization</code></li>
     * <li><code>user</code></li>
     * <li><code>connection</code></li>
     * <li><code>model</code></li>
     * <li><code>sync</code></li>
     * <li><code>sync_execution</code></li>
     * <li><code>bulk_sync</code></li>
     * <li><code>bulk_sync_execution</code></li>
     * </ul>
     * <p>Examples:</p>
     * <ul>
     * <li>A model sync execution resolves to a <code>sync_execution</code> and includes a <code>sync</code>
     * relationship.</li>
     * <li>A bulk sync execution resolves to a <code>bulk_sync_execution</code>, includes a
     * <code>bulk_sync</code> relationship, and may include <code>context.schema_ids</code>.</li>
     * </ul>
     * <p>If the UUID does not exist, the endpoint returns <code>404</code>.</p>
     */
    public PolytomicHttpResponse<EntityResponseEnvelope> getForPartner(String id, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/organizations/entities")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PolytomicHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EntityResponseEnvelope.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PolytomicApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PolytomicException("Network error executing HTTP request", e);
        }
    }
}
