/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.harbors.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import com.polytomic.api.types.HarborSourceReference;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ResolveHarborSourceMappingsRequest.Builder.class)
public final class ResolveHarborSourceMappingsRequest {
    private final Optional<List<HarborSourceReference>> sources;

    private final Map<String, Object> additionalProperties;

    private ResolveHarborSourceMappingsRequest(
            Optional<List<HarborSourceReference>> sources, Map<String, Object> additionalProperties) {
        this.sources = sources;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Source tables to resolve. Answered in request order; maximum 200 entries, each naming at most 500 fields.
     */
    @JsonProperty("sources")
    public Optional<List<HarborSourceReference>> getSources() {
        return sources;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ResolveHarborSourceMappingsRequest
                && equalTo((ResolveHarborSourceMappingsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ResolveHarborSourceMappingsRequest other) {
        return sources.equals(other.sources);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.sources);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<HarborSourceReference>> sources = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(ResolveHarborSourceMappingsRequest other) {
            sources(other.getSources());
            return this;
        }

        /**
         * <p>Source tables to resolve. Answered in request order; maximum 200 entries, each naming at most 500 fields.</p>
         */
        @JsonSetter(value = "sources", nulls = Nulls.SKIP)
        public Builder sources(Optional<List<HarborSourceReference>> sources) {
            this.sources = sources;
            return this;
        }

        public Builder sources(List<HarborSourceReference> sources) {
            this.sources = Optional.ofNullable(sources);
            return this;
        }

        public ResolveHarborSourceMappingsRequest build() {
            return new ResolveHarborSourceMappingsRequest(sources, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
