/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.permissions.roles;

import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.resources.permissions.roles.requests.CreateRoleRequest;
import com.polytomic.api.resources.permissions.roles.requests.UpdateRoleRequest;
import com.polytomic.api.types.RoleListResponseEnvelope;
import com.polytomic.api.types.RoleResponseEnvelope;
import java.util.concurrent.CompletableFuture;

public class AsyncRolesClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawRolesClient rawClient;

    public AsyncRolesClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawRolesClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawRolesClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<RoleListResponseEnvelope> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    public CompletableFuture<RoleListResponseEnvelope> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<RoleResponseEnvelope> create(CreateRoleRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    public CompletableFuture<RoleResponseEnvelope> create(CreateRoleRequest request, RequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<RoleResponseEnvelope> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    public CompletableFuture<RoleResponseEnvelope> get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<RoleResponseEnvelope> update(String id, UpdateRoleRequest request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    public CompletableFuture<RoleResponseEnvelope> update(
            String id, UpdateRoleRequest request, RequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> remove(String id) {
        return this.rawClient.remove(id).thenApply(response -> response.body());
    }

    public CompletableFuture<Void> remove(String id, RequestOptions requestOptions) {
        return this.rawClient.remove(id, requestOptions).thenApply(response -> response.body());
    }
}
