/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.jobs;

import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.types.JobResponseEnvelope;
import java.util.concurrent.CompletableFuture;

public class AsyncJobsClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawJobsClient rawClient;

    public AsyncJobsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawJobsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawJobsClient withRawResponse() {
        return this.rawClient;
    }

    public CompletableFuture<JobResponseEnvelope> get(String id, String type) {
        return this.rawClient.get(id, type).thenApply(response -> response.body());
    }

    public CompletableFuture<JobResponseEnvelope> get(String id, String type, RequestOptions requestOptions) {
        return this.rawClient.get(id, type, requestOptions).thenApply(response -> response.body());
    }
}
