/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.bulksync;

import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.IdempotentRequestOptions;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.core.Suppliers;
import com.polytomic.api.resources.bulksync.executions.AsyncExecutionsClient;
import com.polytomic.api.resources.bulksync.requests.BulkSyncDeleteRequest;
import com.polytomic.api.resources.bulksync.requests.BulkSyncGetRequest;
import com.polytomic.api.resources.bulksync.requests.BulkSyncGetSourceRequest;
import com.polytomic.api.resources.bulksync.requests.BulkSyncListRequest;
import com.polytomic.api.resources.bulksync.requests.CreateBulkSyncRequest;
import com.polytomic.api.resources.bulksync.requests.StartBulkSyncRequest;
import com.polytomic.api.resources.bulksync.requests.UpdateBulkSyncRequest;
import com.polytomic.api.resources.bulksync.schedules.AsyncSchedulesClient;
import com.polytomic.api.resources.bulksync.schemas.AsyncSchemasClient;
import com.polytomic.api.types.ActivateSyncEnvelope;
import com.polytomic.api.types.ActivateSyncInput;
import com.polytomic.api.types.BulkSyncDestEnvelope;
import com.polytomic.api.types.BulkSyncExecutionEnvelope;
import com.polytomic.api.types.BulkSyncListEnvelope;
import com.polytomic.api.types.BulkSyncResponseEnvelope;
import com.polytomic.api.types.BulkSyncSourceEnvelope;
import com.polytomic.api.types.BulkSyncStatusEnvelope;
import com.polytomic.api.types.CancelBulkSyncResponseEnvelope;
import java.util.concurrent.CompletableFuture;
import java.util.function.Supplier;

public class AsyncBulkSyncClient {
    protected final ClientOptions clientOptions;

    private final AsyncRawBulkSyncClient rawClient;

    protected final Supplier<AsyncExecutionsClient> executionsClient;

    protected final Supplier<AsyncSchemasClient> schemasClient;

    protected final Supplier<AsyncSchedulesClient> schedulesClient;

    public AsyncBulkSyncClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new AsyncRawBulkSyncClient(clientOptions);
        this.executionsClient = Suppliers.memoize(() -> new AsyncExecutionsClient(clientOptions));
        this.schemasClient = Suppliers.memoize(() -> new AsyncSchemasClient(clientOptions));
        this.schedulesClient = Suppliers.memoize(() -> new AsyncSchedulesClient(clientOptions));
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public AsyncRawBulkSyncClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Lists bulk syncs in the caller's organization.
     * <p>Results are ordered by <code>updated_at</code> descending, with <code>id</code> as a tiebreaker for
     * syncs modified at the same instant. Pagination uses an opaque
     * <code>pagination.next_page_token</code> returned in the response; pass it back as the
     * <code>page_token</code> query parameter to fetch the next page. The <code>limit</code> parameter is
     * optional, and the default and maximum page size is 50 syncs.</p>
     * <blockquote>
     * <p>📘 To retrieve a specific sync, use
     * <a href="../../../api-reference/bulk-sync/get"><code>GET /api/bulk/syncs/{id}</code></a>
     * instead of filtering the list client-side.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncListEnvelope> list() {
        return this.rawClient.list().thenApply(response -> response.body());
    }

    /**
     * Lists bulk syncs in the caller's organization.
     * <p>Results are ordered by <code>updated_at</code> descending, with <code>id</code> as a tiebreaker for
     * syncs modified at the same instant. Pagination uses an opaque
     * <code>pagination.next_page_token</code> returned in the response; pass it back as the
     * <code>page_token</code> query parameter to fetch the next page. The <code>limit</code> parameter is
     * optional, and the default and maximum page size is 50 syncs.</p>
     * <blockquote>
     * <p>📘 To retrieve a specific sync, use
     * <a href="../../../api-reference/bulk-sync/get"><code>GET /api/bulk/syncs/{id}</code></a>
     * instead of filtering the list client-side.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncListEnvelope> list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists bulk syncs in the caller's organization.
     * <p>Results are ordered by <code>updated_at</code> descending, with <code>id</code> as a tiebreaker for
     * syncs modified at the same instant. Pagination uses an opaque
     * <code>pagination.next_page_token</code> returned in the response; pass it back as the
     * <code>page_token</code> query parameter to fetch the next page. The <code>limit</code> parameter is
     * optional, and the default and maximum page size is 50 syncs.</p>
     * <blockquote>
     * <p>📘 To retrieve a specific sync, use
     * <a href="../../../api-reference/bulk-sync/get"><code>GET /api/bulk/syncs/{id}</code></a>
     * instead of filtering the list client-side.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncListEnvelope> list(BulkSyncListRequest request) {
        return this.rawClient.list(request).thenApply(response -> response.body());
    }

    /**
     * Lists bulk syncs in the caller's organization.
     * <p>Results are ordered by <code>updated_at</code> descending, with <code>id</code> as a tiebreaker for
     * syncs modified at the same instant. Pagination uses an opaque
     * <code>pagination.next_page_token</code> returned in the response; pass it back as the
     * <code>page_token</code> query parameter to fetch the next page. The <code>limit</code> parameter is
     * optional, and the default and maximum page size is 50 syncs.</p>
     * <blockquote>
     * <p>📘 To retrieve a specific sync, use
     * <a href="../../../api-reference/bulk-sync/get"><code>GET /api/bulk/syncs/{id}</code></a>
     * instead of filtering the list client-side.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncListEnvelope> list(BulkSyncListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Creates a new bulk sync.
     * <p>Bulk syncs are used for the ELT pattern (Extract, Load, and Transform), where you want to sync un-transformed data to your data warehouses, databases, or cloud storage buckets like S3.</p>
     * <p>All of the functionality described in <a href="https://docs.polytomic.com/docs/bulk-syncs">the product
     * documentation</a> is configurable via
     * the API.</p>
     * <p>Sample code examples:</p>
     * <ul>
     * <li><a href="../../../guides/code-examples/bulk-sync-elt-from-salesforce-to-s-3">Bulk sync (ELT) from Salesforce to S3</a></li>
     * <li><a href="../../../guides/code-examples/bulk-sync-elt-from-salesforce-to-snowflake">Bulk sync (ELT) from Salesforce to Snowflake</a></li>
     * <li><a href="../../../guides/code-examples/bulk-sync-elt-from-hub-spot-to-postgre-sql">Bulk sync (ELT) from HubSpot to PostgreSQL</a></li>
     * </ul>
     * <h2>Connection specific configuration</h2>
     * <p>The <code>destination_configuration</code> is integration-specific configuration for the
     * selected bulk sync destination. This includes settings such as the output schema
     * and is required when creating a new sync.</p>
     * <p>The <code>source_configuration</code> is optional. It allows configuration for how
     * Polytomic reads data from the source connection. This will not be available for
     * integrations that do not support additional configuration.</p>
     * <p>Consult the <a href="../../../guides/configuring-your-connections/overview">connection configurations</a>
     * to see configurations for particular integrations (for example, <a href="../../../guides/configuring-your-connections/connections/postgre-sql#source-1">here</a> is the available source configuration for the PostgreSQL bulk sync source).</p>
     * <h2>Defaults and selection behavior</h2>
     * <p>If <code>schemas</code> is omitted, the sync is created with all available source schemas
     * selected. Pass <code>schemas</code> explicitly if you want the initial sync to include
     * only a subset of tables or objects.</p>
     * <p>Schedule times are interpreted in UTC.</p>
     * <p>When omitted, automatic discovery defaults are conservative:</p>
     * <ul>
     * <li><code>automatically_add_new_objects</code> defaults to not enabling newly discovered
     * source objects automatically.</li>
     * <li><code>automatically_add_new_fields</code> defaults to enabling newly discovered fields
     * on already selected objects.</li>
     * <li><code>normalize_names</code> defaults to enabled.</li>
     * </ul>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> create(CreateBulkSyncRequest request) {
        return this.rawClient.create(request).thenApply(response -> response.body());
    }

    /**
     * Creates a new bulk sync.
     * <p>Bulk syncs are used for the ELT pattern (Extract, Load, and Transform), where you want to sync un-transformed data to your data warehouses, databases, or cloud storage buckets like S3.</p>
     * <p>All of the functionality described in <a href="https://docs.polytomic.com/docs/bulk-syncs">the product
     * documentation</a> is configurable via
     * the API.</p>
     * <p>Sample code examples:</p>
     * <ul>
     * <li><a href="../../../guides/code-examples/bulk-sync-elt-from-salesforce-to-s-3">Bulk sync (ELT) from Salesforce to S3</a></li>
     * <li><a href="../../../guides/code-examples/bulk-sync-elt-from-salesforce-to-snowflake">Bulk sync (ELT) from Salesforce to Snowflake</a></li>
     * <li><a href="../../../guides/code-examples/bulk-sync-elt-from-hub-spot-to-postgre-sql">Bulk sync (ELT) from HubSpot to PostgreSQL</a></li>
     * </ul>
     * <h2>Connection specific configuration</h2>
     * <p>The <code>destination_configuration</code> is integration-specific configuration for the
     * selected bulk sync destination. This includes settings such as the output schema
     * and is required when creating a new sync.</p>
     * <p>The <code>source_configuration</code> is optional. It allows configuration for how
     * Polytomic reads data from the source connection. This will not be available for
     * integrations that do not support additional configuration.</p>
     * <p>Consult the <a href="../../../guides/configuring-your-connections/overview">connection configurations</a>
     * to see configurations for particular integrations (for example, <a href="../../../guides/configuring-your-connections/connections/postgre-sql#source-1">here</a> is the available source configuration for the PostgreSQL bulk sync source).</p>
     * <h2>Defaults and selection behavior</h2>
     * <p>If <code>schemas</code> is omitted, the sync is created with all available source schemas
     * selected. Pass <code>schemas</code> explicitly if you want the initial sync to include
     * only a subset of tables or objects.</p>
     * <p>Schedule times are interpreted in UTC.</p>
     * <p>When omitted, automatic discovery defaults are conservative:</p>
     * <ul>
     * <li><code>automatically_add_new_objects</code> defaults to not enabling newly discovered
     * source objects automatically.</li>
     * <li><code>automatically_add_new_fields</code> defaults to enabling newly discovered fields
     * on already selected objects.</li>
     * <li><code>normalize_names</code> defaults to enabled.</li>
     * </ul>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> create(
            CreateBulkSyncRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.create(request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a bulk sync by ID.
     * <p>The response includes the sync's top-level configuration — source, destination,
     * schedules, and discovery settings.</p>
     * <ul>
     * <li>To check whether the sync is running and see the most-recent execution result,
     * use <a href="../../../../api-reference/bulk-sync/get-status"><code>GET /api/bulk/syncs/{id}/status</code></a>.</li>
     * <li>To inspect which schemas are selected and how they are configured, use
     * <a href="../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</li>
     * </ul>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> get(String id) {
        return this.rawClient.get(id).thenApply(response -> response.body());
    }

    /**
     * Returns a bulk sync by ID.
     * <p>The response includes the sync's top-level configuration — source, destination,
     * schedules, and discovery settings.</p>
     * <ul>
     * <li>To check whether the sync is running and see the most-recent execution result,
     * use <a href="../../../../api-reference/bulk-sync/get-status"><code>GET /api/bulk/syncs/{id}/status</code></a>.</li>
     * <li>To inspect which schemas are selected and how they are configured, use
     * <a href="../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</li>
     * </ul>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns a bulk sync by ID.
     * <p>The response includes the sync's top-level configuration — source, destination,
     * schedules, and discovery settings.</p>
     * <ul>
     * <li>To check whether the sync is running and see the most-recent execution result,
     * use <a href="../../../../api-reference/bulk-sync/get-status"><code>GET /api/bulk/syncs/{id}/status</code></a>.</li>
     * <li>To inspect which schemas are selected and how they are configured, use
     * <a href="../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</li>
     * </ul>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> get(String id, BulkSyncGetRequest request) {
        return this.rawClient.get(id, request).thenApply(response -> response.body());
    }

    /**
     * Returns a bulk sync by ID.
     * <p>The response includes the sync's top-level configuration — source, destination,
     * schedules, and discovery settings.</p>
     * <ul>
     * <li>To check whether the sync is running and see the most-recent execution result,
     * use <a href="../../../../api-reference/bulk-sync/get-status"><code>GET /api/bulk/syncs/{id}/status</code></a>.</li>
     * <li>To inspect which schemas are selected and how they are configured, use
     * <a href="../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</li>
     * </ul>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> get(
            String id, BulkSyncGetRequest request, RequestOptions requestOptions) {
        return this.rawClient.get(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Updates an existing bulk sync's top-level configuration.
     * <p>Updating a bulk sync is a <strong>full replacement</strong> of the sync's top-level
     * configuration. Every field in the request body is written to the sync; any
     * field you omit is cleared or reset to its default value.</p>
     * <p>To make a partial change — for example, toggling <code>active</code> or swapping a
     * schedule — fetch the current sync with
     * <a href="../../../../api-reference/bulk-sync/get"><code>GET /api/bulk/syncs/{id}</code></a>,
     * modify the fields you want to change, and send the complete object back in
     * the update request.</p>
     * <p>Updates to <code>active</code>, <code>schedules</code>, and <code>policies</code> take effect immediately.
     * Changes to source or destination configuration take effect on the sync's
     * next execution.</p>
     * <p>Because omitted fields are reset to their defaults, the discovery and
     * naming options behave the same as on create when left out:</p>
     * <ul>
     * <li><code>automatically_add_new_objects</code> resets to not enabling newly discovered
     * source objects automatically.</li>
     * <li><code>automatically_add_new_fields</code> resets to enabling newly discovered
     * fields on already selected objects.</li>
     * <li><code>normalize_names</code> resets to enabled.</li>
     * </ul>
     * <p>Send the existing values explicitly if you want to preserve a non-default or
     * non-empty setting, including schema and field selections.</p>
     * <blockquote>
     * <p>📘 Updating schemas</p>
     * <p>Schema updates are not performed through this endpoint. Use the
     * <a href="../../../../api-reference/bulk-sync/schemas/patch">Update Bulk Sync Schemas</a>
     * endpoint to change a subset of schemas, or
     * <a href="../../../../api-reference/bulk-sync/schemas/update">Update Bulk Sync Schema</a>
     * to replace a single schema's configuration.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> update(String id, UpdateBulkSyncRequest request) {
        return this.rawClient.update(id, request).thenApply(response -> response.body());
    }

    /**
     * Updates an existing bulk sync's top-level configuration.
     * <p>Updating a bulk sync is a <strong>full replacement</strong> of the sync's top-level
     * configuration. Every field in the request body is written to the sync; any
     * field you omit is cleared or reset to its default value.</p>
     * <p>To make a partial change — for example, toggling <code>active</code> or swapping a
     * schedule — fetch the current sync with
     * <a href="../../../../api-reference/bulk-sync/get"><code>GET /api/bulk/syncs/{id}</code></a>,
     * modify the fields you want to change, and send the complete object back in
     * the update request.</p>
     * <p>Updates to <code>active</code>, <code>schedules</code>, and <code>policies</code> take effect immediately.
     * Changes to source or destination configuration take effect on the sync's
     * next execution.</p>
     * <p>Because omitted fields are reset to their defaults, the discovery and
     * naming options behave the same as on create when left out:</p>
     * <ul>
     * <li><code>automatically_add_new_objects</code> resets to not enabling newly discovered
     * source objects automatically.</li>
     * <li><code>automatically_add_new_fields</code> resets to enabling newly discovered
     * fields on already selected objects.</li>
     * <li><code>normalize_names</code> resets to enabled.</li>
     * </ul>
     * <p>Send the existing values explicitly if you want to preserve a non-default or
     * non-empty setting, including schema and field selections.</p>
     * <blockquote>
     * <p>📘 Updating schemas</p>
     * <p>Schema updates are not performed through this endpoint. Use the
     * <a href="../../../../api-reference/bulk-sync/schemas/patch">Update Bulk Sync Schemas</a>
     * endpoint to change a subset of schemas, or
     * <a href="../../../../api-reference/bulk-sync/schemas/update">Update Bulk Sync Schema</a>
     * to replace a single schema's configuration.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncResponseEnvelope> update(
            String id, UpdateBulkSyncRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Deletes a bulk sync, cancelling any running executions.
     * <p>Any execution that is currently running is cancelled before the sync record is
     * removed.</p>
     * <blockquote>
     * <p>🚧 All associated schedules, schema configurations, and execution history are
     * deleted along with the sync.</p>
     * </blockquote>
     */
    public CompletableFuture<Void> delete(String id) {
        return this.rawClient.delete(id).thenApply(response -> response.body());
    }

    /**
     * Deletes a bulk sync, cancelling any running executions.
     * <p>Any execution that is currently running is cancelled before the sync record is
     * removed.</p>
     * <blockquote>
     * <p>🚧 All associated schedules, schema configurations, and execution history are
     * deleted along with the sync.</p>
     * </blockquote>
     */
    public CompletableFuture<Void> delete(String id, IdempotentRequestOptions requestOptions) {
        return this.rawClient.delete(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Deletes a bulk sync, cancelling any running executions.
     * <p>Any execution that is currently running is cancelled before the sync record is
     * removed.</p>
     * <blockquote>
     * <p>🚧 All associated schedules, schema configurations, and execution history are
     * deleted along with the sync.</p>
     * </blockquote>
     */
    public CompletableFuture<Void> delete(String id, BulkSyncDeleteRequest request) {
        return this.rawClient.delete(id, request).thenApply(response -> response.body());
    }

    /**
     * Deletes a bulk sync, cancelling any running executions.
     * <p>Any execution that is currently running is cancelled before the sync record is
     * removed.</p>
     * <blockquote>
     * <p>🚧 All associated schedules, schema configurations, and execution history are
     * deleted along with the sync.</p>
     * </blockquote>
     */
    public CompletableFuture<Void> delete(
            String id, BulkSyncDeleteRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.delete(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Sets whether a bulk sync is active.
     * <p>Only active syncs are eligible to execute on their configured schedule.
     * Deactivating a sync prevents future scheduled runs and requests cancellation of
     * any execution that is currently in progress.</p>
     * <blockquote>
     * <p>📘 To start or stop a running execution directly, use
     * <a href="../../../../../api-reference/bulk-sync/start"><code>POST /api/bulk/syncs/{id}/executions</code></a>
     * or
     * <a href="../../../../../api-reference/bulk-sync/cancel"><code>POST /api/bulk/syncs/{id}/cancel</code></a>.</p>
     * </blockquote>
     */
    public CompletableFuture<ActivateSyncEnvelope> activate(String id, ActivateSyncInput request) {
        return this.rawClient.activate(id, request).thenApply(response -> response.body());
    }

    /**
     * Sets whether a bulk sync is active.
     * <p>Only active syncs are eligible to execute on their configured schedule.
     * Deactivating a sync prevents future scheduled runs and requests cancellation of
     * any execution that is currently in progress.</p>
     * <blockquote>
     * <p>📘 To start or stop a running execution directly, use
     * <a href="../../../../../api-reference/bulk-sync/start"><code>POST /api/bulk/syncs/{id}/executions</code></a>
     * or
     * <a href="../../../../../api-reference/bulk-sync/cancel"><code>POST /api/bulk/syncs/{id}/cancel</code></a>.</p>
     * </blockquote>
     */
    public CompletableFuture<ActivateSyncEnvelope> activate(
            String id, ActivateSyncInput request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.activate(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Requests cancellation of any running executions on a bulk sync.
     * <p>Cancellation is asynchronous. A successful response means the cancellation
     * signal has been queued; the running execution continues until the signal is
     * processed. Poll <code>GET /api/bulk/syncs/{id}/status</code> until the current execution
     * reaches a terminal state (<code>completed</code>, <code>canceled</code>, or <code>failed</code>) to confirm
     * cancellation has taken effect.</p>
     */
    public CompletableFuture<CancelBulkSyncResponseEnvelope> cancel(String id) {
        return this.rawClient.cancel(id).thenApply(response -> response.body());
    }

    /**
     * Requests cancellation of any running executions on a bulk sync.
     * <p>Cancellation is asynchronous. A successful response means the cancellation
     * signal has been queued; the running execution continues until the signal is
     * processed. Poll <code>GET /api/bulk/syncs/{id}/status</code> until the current execution
     * reaches a terminal state (<code>completed</code>, <code>canceled</code>, or <code>failed</code>) to confirm
     * cancellation has taken effect.</p>
     */
    public CompletableFuture<CancelBulkSyncResponseEnvelope> cancel(
            String id, IdempotentRequestOptions requestOptions) {
        return this.rawClient.cancel(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Starts a new execution of a bulk sync.
     * <p>This endpoint returns the execution record immediately after the run is queued
     * or started. Use the execution ID with the bulk-sync execution endpoints if you
     * need to monitor progress in detail.</p>
     * <h2>Execution modes</h2>
     * <ul>
     * <li>Set <code>test=true</code> to validate the sync without writing to the destination.</li>
     * <li>Use <code>resync_mode</code> for destructive or full-refresh style reruns.</li>
     * <li><code>test</code> and <code>resync_mode</code> are mutually exclusive.</li>
     * </ul>
     * <p>The legacy <code>resync</code> boolean is no longer accepted on this v5 endpoint. Send
     * <code>resync_mode</code> instead.</p>
     * <p>If another execution is already running, the endpoint returns <code>409 Conflict</code>.</p>
     */
    public CompletableFuture<BulkSyncExecutionEnvelope> start(String id) {
        return this.rawClient.start(id).thenApply(response -> response.body());
    }

    /**
     * Starts a new execution of a bulk sync.
     * <p>This endpoint returns the execution record immediately after the run is queued
     * or started. Use the execution ID with the bulk-sync execution endpoints if you
     * need to monitor progress in detail.</p>
     * <h2>Execution modes</h2>
     * <ul>
     * <li>Set <code>test=true</code> to validate the sync without writing to the destination.</li>
     * <li>Use <code>resync_mode</code> for destructive or full-refresh style reruns.</li>
     * <li><code>test</code> and <code>resync_mode</code> are mutually exclusive.</li>
     * </ul>
     * <p>The legacy <code>resync</code> boolean is no longer accepted on this v5 endpoint. Send
     * <code>resync_mode</code> instead.</p>
     * <p>If another execution is already running, the endpoint returns <code>409 Conflict</code>.</p>
     */
    public CompletableFuture<BulkSyncExecutionEnvelope> start(String id, IdempotentRequestOptions requestOptions) {
        return this.rawClient.start(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Starts a new execution of a bulk sync.
     * <p>This endpoint returns the execution record immediately after the run is queued
     * or started. Use the execution ID with the bulk-sync execution endpoints if you
     * need to monitor progress in detail.</p>
     * <h2>Execution modes</h2>
     * <ul>
     * <li>Set <code>test=true</code> to validate the sync without writing to the destination.</li>
     * <li>Use <code>resync_mode</code> for destructive or full-refresh style reruns.</li>
     * <li><code>test</code> and <code>resync_mode</code> are mutually exclusive.</li>
     * </ul>
     * <p>The legacy <code>resync</code> boolean is no longer accepted on this v5 endpoint. Send
     * <code>resync_mode</code> instead.</p>
     * <p>If another execution is already running, the endpoint returns <code>409 Conflict</code>.</p>
     */
    public CompletableFuture<BulkSyncExecutionEnvelope> start(String id, StartBulkSyncRequest request) {
        return this.rawClient.start(id, request).thenApply(response -> response.body());
    }

    /**
     * Starts a new execution of a bulk sync.
     * <p>This endpoint returns the execution record immediately after the run is queued
     * or started. Use the execution ID with the bulk-sync execution endpoints if you
     * need to monitor progress in detail.</p>
     * <h2>Execution modes</h2>
     * <ul>
     * <li>Set <code>test=true</code> to validate the sync without writing to the destination.</li>
     * <li>Use <code>resync_mode</code> for destructive or full-refresh style reruns.</li>
     * <li><code>test</code> and <code>resync_mode</code> are mutually exclusive.</li>
     * </ul>
     * <p>The legacy <code>resync</code> boolean is no longer accepted on this v5 endpoint. Send
     * <code>resync_mode</code> instead.</p>
     * <p>If another execution is already running, the endpoint returns <code>409 Conflict</code>.</p>
     */
    public CompletableFuture<BulkSyncExecutionEnvelope> start(
            String id, StartBulkSyncRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.start(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Returns the current status of a bulk sync.
     * <p>The response includes the sync's current active/inactive state together with
     * information about the most recent execution — its status, start time, and any
     * errors — making this endpoint well-suited for health checks and monitoring
     * dashboards.</p>
     * <p>For the complete execution history, use
     * <a href="../../../../../api-reference/bulk-sync/executions/list"><code>GET /api/bulk/syncs/{id}/executions</code></a>.
     * For the full details of a specific run, including per-schema breakdowns, use
     * <a href="../../../../../api-reference/bulk-sync/executions/get"><code>GET /api/bulk/syncs/{id}/executions/{exec_id}</code></a>.</p>
     */
    public CompletableFuture<BulkSyncStatusEnvelope> getStatus(String id) {
        return this.rawClient.getStatus(id).thenApply(response -> response.body());
    }

    /**
     * Returns the current status of a bulk sync.
     * <p>The response includes the sync's current active/inactive state together with
     * information about the most recent execution — its status, start time, and any
     * errors — making this endpoint well-suited for health checks and monitoring
     * dashboards.</p>
     * <p>For the complete execution history, use
     * <a href="../../../../../api-reference/bulk-sync/executions/list"><code>GET /api/bulk/syncs/{id}/executions</code></a>.
     * For the full details of a specific run, including per-schema breakdowns, use
     * <a href="../../../../../api-reference/bulk-sync/executions/get"><code>GET /api/bulk/syncs/{id}/executions/{exec_id}</code></a>.</p>
     */
    public CompletableFuture<BulkSyncStatusEnvelope> getStatus(String id, RequestOptions requestOptions) {
        return this.rawClient.getStatus(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists the schemas (tables or objects) available on a connection for use as a bulk sync source, optionally including per-schema field details.
     * <p>The response reflects what the
     * connection currently has cached; if the upstream source has changed, trigger
     * a refresh first with
     * <a href="../../../../../api-reference/schemas/refresh"><code>POST /api/connections/{id}/schemas/refresh</code></a>.</p>
     * <p>These are the schemas available for selection, not the schemas already
     * configured on any particular sync. To inspect schemas on a running sync, use
     * <a href="../../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</p>
     * <p>Pass <code>include_fields=true</code> to receive per-schema field details in a single call.
     * Omit it when you only need the schema list, as field enumeration can be slow for
     * large sources.</p>
     */
    public CompletableFuture<BulkSyncSourceEnvelope> getSource(String id) {
        return this.rawClient.getSource(id).thenApply(response -> response.body());
    }

    /**
     * Lists the schemas (tables or objects) available on a connection for use as a bulk sync source, optionally including per-schema field details.
     * <p>The response reflects what the
     * connection currently has cached; if the upstream source has changed, trigger
     * a refresh first with
     * <a href="../../../../../api-reference/schemas/refresh"><code>POST /api/connections/{id}/schemas/refresh</code></a>.</p>
     * <p>These are the schemas available for selection, not the schemas already
     * configured on any particular sync. To inspect schemas on a running sync, use
     * <a href="../../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</p>
     * <p>Pass <code>include_fields=true</code> to receive per-schema field details in a single call.
     * Omit it when you only need the schema list, as field enumeration can be slow for
     * large sources.</p>
     */
    public CompletableFuture<BulkSyncSourceEnvelope> getSource(String id, RequestOptions requestOptions) {
        return this.rawClient.getSource(id, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Lists the schemas (tables or objects) available on a connection for use as a bulk sync source, optionally including per-schema field details.
     * <p>The response reflects what the
     * connection currently has cached; if the upstream source has changed, trigger
     * a refresh first with
     * <a href="../../../../../api-reference/schemas/refresh"><code>POST /api/connections/{id}/schemas/refresh</code></a>.</p>
     * <p>These are the schemas available for selection, not the schemas already
     * configured on any particular sync. To inspect schemas on a running sync, use
     * <a href="../../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</p>
     * <p>Pass <code>include_fields=true</code> to receive per-schema field details in a single call.
     * Omit it when you only need the schema list, as field enumeration can be slow for
     * large sources.</p>
     */
    public CompletableFuture<BulkSyncSourceEnvelope> getSource(String id, BulkSyncGetSourceRequest request) {
        return this.rawClient.getSource(id, request).thenApply(response -> response.body());
    }

    /**
     * Lists the schemas (tables or objects) available on a connection for use as a bulk sync source, optionally including per-schema field details.
     * <p>The response reflects what the
     * connection currently has cached; if the upstream source has changed, trigger
     * a refresh first with
     * <a href="../../../../../api-reference/schemas/refresh"><code>POST /api/connections/{id}/schemas/refresh</code></a>.</p>
     * <p>These are the schemas available for selection, not the schemas already
     * configured on any particular sync. To inspect schemas on a running sync, use
     * <a href="../../../../../api-reference/bulk-sync/schemas/list"><code>GET /api/bulk/syncs/{id}/schemas</code></a>.</p>
     * <p>Pass <code>include_fields=true</code> to receive per-schema field details in a single call.
     * Omit it when you only need the schema list, as field enumeration can be slow for
     * large sources.</p>
     */
    public CompletableFuture<BulkSyncSourceEnvelope> getSource(
            String id, BulkSyncGetSourceRequest request, RequestOptions requestOptions) {
        return this.rawClient.getSource(id, request, requestOptions).thenApply(response -> response.body());
    }

    /**
     * Describes the destination configuration schema a connection accepts when used as a bulk sync destination.
     * <p>The response is a JSON Schema object describing the shape of the
     * <code>destination_configuration</code> field you must supply when
     * <a href="../../../../../api-reference/bulk-sync/create">creating</a> or
     * <a href="../../../../../api-reference/bulk-sync/update">updating</a> a bulk sync that uses this
     * connection as its destination. Required fields vary by connection type.</p>
     * <blockquote>
     * <p>📘 Fetch this endpoint once per connection type rather than once per sync.
     * The configuration schema is the same for all syncs sharing the same
     * destination connection.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncDestEnvelope> getDestination(String id) {
        return this.rawClient.getDestination(id).thenApply(response -> response.body());
    }

    /**
     * Describes the destination configuration schema a connection accepts when used as a bulk sync destination.
     * <p>The response is a JSON Schema object describing the shape of the
     * <code>destination_configuration</code> field you must supply when
     * <a href="../../../../../api-reference/bulk-sync/create">creating</a> or
     * <a href="../../../../../api-reference/bulk-sync/update">updating</a> a bulk sync that uses this
     * connection as its destination. Required fields vary by connection type.</p>
     * <blockquote>
     * <p>📘 Fetch this endpoint once per connection type rather than once per sync.
     * The configuration schema is the same for all syncs sharing the same
     * destination connection.</p>
     * </blockquote>
     */
    public CompletableFuture<BulkSyncDestEnvelope> getDestination(String id, RequestOptions requestOptions) {
        return this.rawClient.getDestination(id, requestOptions).thenApply(response -> response.body());
    }

    public AsyncExecutionsClient executions() {
        return this.executionsClient.get();
    }

    public AsyncSchemasClient schemas() {
        return this.schemasClient.get();
    }

    public AsyncSchedulesClient schedules() {
        return this.schedulesClient.get();
    }
}
