/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.connections.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.polytomic.api.core.ObjectMappers;
import java.util.Map;

public final class ConnectionsGetConnectionTypeSchemaRequest {
    private final Map<String, Object> additionalProperties;

    private ConnectionsGetConnectionTypeSchemaRequest(Map<String, Object> additionalProperties) {
        this.additionalProperties = additionalProperties;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ConnectionsGetConnectionTypeSchemaRequest;
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }
}
