/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.events;

import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.resources.events.requests.EventsListRequest;
import com.polytomic.api.types.EventTypesEnvelope;
import com.polytomic.api.types.EventsEnvelope;

public class EventsClient {
    protected final ClientOptions clientOptions;

    private final RawEventsClient rawClient;

    public EventsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawEventsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawEventsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Lists audit events for the caller's organization.
     * <p>Results are paginated. If more events are available, the response includes
     * <code>pagination.next_page_token</code>; pass that token back unchanged to continue from
     * the last item you received.</p>
     * <p>Filter by event type using the <code>event_type</code> query parameter. Pass one of the
     * identifiers returned by <a href="../../api-reference/events/get-types"><code>GET /api/events_types</code></a> to
     * narrow results to a specific category of activity.</p>
     * <blockquote>
     * <p>📘 Events reflect audit activity scoped to the caller's organization.
     * The log captures both user-initiated and API-initiated actions.</p>
     * </blockquote>
     */
    public EventsEnvelope list() {
        return this.rawClient.list().body();
    }

    /**
     * Lists audit events for the caller's organization.
     * <p>Results are paginated. If more events are available, the response includes
     * <code>pagination.next_page_token</code>; pass that token back unchanged to continue from
     * the last item you received.</p>
     * <p>Filter by event type using the <code>event_type</code> query parameter. Pass one of the
     * identifiers returned by <a href="../../api-reference/events/get-types"><code>GET /api/events_types</code></a> to
     * narrow results to a specific category of activity.</p>
     * <blockquote>
     * <p>📘 Events reflect audit activity scoped to the caller's organization.
     * The log captures both user-initiated and API-initiated actions.</p>
     * </blockquote>
     */
    public EventsEnvelope list(RequestOptions requestOptions) {
        return this.rawClient.list(requestOptions).body();
    }

    /**
     * Lists audit events for the caller's organization.
     * <p>Results are paginated. If more events are available, the response includes
     * <code>pagination.next_page_token</code>; pass that token back unchanged to continue from
     * the last item you received.</p>
     * <p>Filter by event type using the <code>event_type</code> query parameter. Pass one of the
     * identifiers returned by <a href="../../api-reference/events/get-types"><code>GET /api/events_types</code></a> to
     * narrow results to a specific category of activity.</p>
     * <blockquote>
     * <p>📘 Events reflect audit activity scoped to the caller's organization.
     * The log captures both user-initiated and API-initiated actions.</p>
     * </blockquote>
     */
    public EventsEnvelope list(EventsListRequest request) {
        return this.rawClient.list(request).body();
    }

    /**
     * Lists audit events for the caller's organization.
     * <p>Results are paginated. If more events are available, the response includes
     * <code>pagination.next_page_token</code>; pass that token back unchanged to continue from
     * the last item you received.</p>
     * <p>Filter by event type using the <code>event_type</code> query parameter. Pass one of the
     * identifiers returned by <a href="../../api-reference/events/get-types"><code>GET /api/events_types</code></a> to
     * narrow results to a specific category of activity.</p>
     * <blockquote>
     * <p>📘 Events reflect audit activity scoped to the caller's organization.
     * The log captures both user-initiated and API-initiated actions.</p>
     * </blockquote>
     */
    public EventsEnvelope list(EventsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(request, requestOptions).body();
    }

    /**
     * Returns the set of event type identifiers supported by GET /api/events.
     * <p>Use the identifiers returned here as the <code>event_type</code> filter value when calling
     * <a href="../../api-reference/events/list"><code>GET /api/events</code></a>.</p>
     */
    public EventTypesEnvelope getTypes() {
        return this.rawClient.getTypes().body();
    }

    /**
     * Returns the set of event type identifiers supported by GET /api/events.
     * <p>Use the identifiers returned here as the <code>event_type</code> filter value when calling
     * <a href="../../api-reference/events/list"><code>GET /api/events</code></a>.</p>
     */
    public EventTypesEnvelope getTypes(RequestOptions requestOptions) {
        return this.rawClient.getTypes(requestOptions).body();
    }
}
