/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.modelsync.executions;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.MediaTypes;
import com.polytomic.api.core.ObjectMappers;
import com.polytomic.api.core.PolytomicApiException;
import com.polytomic.api.core.PolytomicException;
import com.polytomic.api.core.PolytomicHttpResponse;
import com.polytomic.api.core.QueryStringMapper;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.errors.BadRequestError;
import com.polytomic.api.errors.ForbiddenError;
import com.polytomic.api.errors.InternalServerError;
import com.polytomic.api.errors.NotFoundError;
import com.polytomic.api.errors.UnauthorizedError;
import com.polytomic.api.resources.modelsync.executions.requests.ExecutionsGetLogUrlsRequest;
import com.polytomic.api.resources.modelsync.executions.requests.ExecutionsGetLogsRequest;
import com.polytomic.api.resources.modelsync.executions.requests.ExecutionsGetRequest;
import com.polytomic.api.resources.modelsync.executions.requests.ExecutionsListRequest;
import com.polytomic.api.resources.modelsync.executions.requests.UpdateExecutionRequest;
import com.polytomic.api.types.ApiError;
import com.polytomic.api.types.ExecutionLogsResponseEnvelope;
import com.polytomic.api.types.GetExecutionResponseEnvelope;
import com.polytomic.api.types.ListExecutionResponseEnvelope;
import com.polytomic.api.types.RestErrResponse;
import com.polytomic.api.types.V2ExecutionLogType;
import java.io.IOException;
import java.util.concurrent.CompletableFuture;
import okhttp3.Call;
import okhttp3.Callback;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;
import org.jetbrains.annotations.NotNull;

public class AsyncRawExecutionsClient {
    protected final ClientOptions clientOptions;

    public AsyncRawExecutionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public CompletableFuture<PolytomicHttpResponse<ListExecutionResponseEnvelope>> list(String syncId) {
        return list(syncId, ExecutionsListRequest.builder().build());
    }

    public CompletableFuture<PolytomicHttpResponse<ListExecutionResponseEnvelope>> list(
            String syncId, RequestOptions requestOptions) {
        return list(syncId, ExecutionsListRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<PolytomicHttpResponse<ListExecutionResponseEnvelope>> list(
            String syncId, ExecutionsListRequest request) {
        return list(syncId, request, null);
    }

    public CompletableFuture<PolytomicHttpResponse<ListExecutionResponseEnvelope>> list(
            String syncId, ExecutionsListRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/syncs")
                .addPathSegment(syncId)
                .addPathSegments("executions");
        if (request.getPageToken().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "page_token", request.getPageToken().get(), false);
        }
        if (request.getOnlyCompleted().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "only_completed", request.getOnlyCompleted().get(), false);
        }
        if (request.getAscending().isPresent()) {
            QueryStringMapper.addQueryParameter(
                    httpUrl, "ascending", request.getAscending().get(), false);
        }
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PolytomicHttpResponse<ListExecutionResponseEnvelope>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PolytomicHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, ListExecutionResponseEnvelope.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RestErrResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PolytomicApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> get(String syncId, String id) {
        return get(syncId, id, ExecutionsGetRequest.builder().build());
    }

    public CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> get(
            String syncId, String id, RequestOptions requestOptions) {
        return get(syncId, id, ExecutionsGetRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> get(
            String syncId, String id, ExecutionsGetRequest request) {
        return get(syncId, id, request, null);
    }

    public CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> get(
            String syncId, String id, ExecutionsGetRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/syncs")
                .addPathSegment(syncId)
                .addPathSegments("executions")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PolytomicHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, GetExecutionResponseEnvelope.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RestErrResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PolytomicApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> update(
            String syncId, String id, UpdateExecutionRequest request) {
        return update(syncId, id, request, null);
    }

    public CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> update(
            String syncId, String id, UpdateExecutionRequest request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/syncs")
                .addPathSegment(syncId)
                .addPathSegments("executions")
                .addPathSegment(id);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PolytomicException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PolytomicHttpResponse<GetExecutionResponseEnvelope>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PolytomicHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, GetExecutionResponseEnvelope.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RestErrResponse.class),
                                        response));
                                return;
                            case 403:
                                future.completeExceptionally(new ForbiddenError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PolytomicApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<PolytomicHttpResponse<ExecutionLogsResponseEnvelope>> getLogUrls(
            String syncId, String id, V2ExecutionLogType type) {
        return getLogUrls(
                syncId, id, type, ExecutionsGetLogUrlsRequest.builder().build());
    }

    public CompletableFuture<PolytomicHttpResponse<ExecutionLogsResponseEnvelope>> getLogUrls(
            String syncId, String id, V2ExecutionLogType type, RequestOptions requestOptions) {
        return getLogUrls(
                syncId, id, type, ExecutionsGetLogUrlsRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<PolytomicHttpResponse<ExecutionLogsResponseEnvelope>> getLogUrls(
            String syncId, String id, V2ExecutionLogType type, ExecutionsGetLogUrlsRequest request) {
        return getLogUrls(syncId, id, type, request, null);
    }

    public CompletableFuture<PolytomicHttpResponse<ExecutionLogsResponseEnvelope>> getLogUrls(
            String syncId,
            String id,
            V2ExecutionLogType type,
            ExecutionsGetLogUrlsRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/syncs")
                .addPathSegment(syncId)
                .addPathSegments("executions")
                .addPathSegment(id)
                .addPathSegment(type.toString());
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PolytomicHttpResponse<ExecutionLogsResponseEnvelope>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    if (response.isSuccessful()) {
                        future.complete(new PolytomicHttpResponse<>(
                                ObjectMappers.JSON_MAPPER.readValue(
                                        responseBodyString, ExecutionLogsResponseEnvelope.class),
                                response));
                        return;
                    }
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RestErrResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PolytomicApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
            }
        });
        return future;
    }

    public CompletableFuture<PolytomicHttpResponse<Void>> getLogs(
            String syncId, String id, V2ExecutionLogType type, String filename) {
        return getLogs(
                syncId, id, type, filename, ExecutionsGetLogsRequest.builder().build());
    }

    public CompletableFuture<PolytomicHttpResponse<Void>> getLogs(
            String syncId, String id, V2ExecutionLogType type, String filename, RequestOptions requestOptions) {
        return getLogs(
                syncId, id, type, filename, ExecutionsGetLogsRequest.builder().build(), requestOptions);
    }

    public CompletableFuture<PolytomicHttpResponse<Void>> getLogs(
            String syncId, String id, V2ExecutionLogType type, String filename, ExecutionsGetLogsRequest request) {
        return getLogs(syncId, id, type, filename, request, null);
    }

    public CompletableFuture<PolytomicHttpResponse<Void>> getLogs(
            String syncId,
            String id,
            V2ExecutionLogType type,
            String filename,
            ExecutionsGetLogsRequest request,
            RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/syncs")
                .addPathSegment(syncId)
                .addPathSegments("executions")
                .addPathSegment(id)
                .addPathSegment(type.toString())
                .addPathSegment(filename);
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        CompletableFuture<PolytomicHttpResponse<Void>> future = new CompletableFuture<>();
        client.newCall(okhttpRequest).enqueue(new Callback() {
            @Override
            public void onResponse(@NotNull Call call, @NotNull Response response) throws IOException {
                try (ResponseBody responseBody = response.body()) {
                    if (response.isSuccessful()) {
                        future.complete(new PolytomicHttpResponse<>(null, response));
                        return;
                    }
                    String responseBodyString = responseBody != null ? responseBody.string() : "{}";
                    try {
                        switch (response.code()) {
                            case 400:
                                future.completeExceptionally(new BadRequestError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 401:
                                future.completeExceptionally(new UnauthorizedError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, RestErrResponse.class),
                                        response));
                                return;
                            case 404:
                                future.completeExceptionally(new NotFoundError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                            case 500:
                                future.completeExceptionally(new InternalServerError(
                                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class),
                                        response));
                                return;
                        }
                    } catch (JsonProcessingException ignored) {
                        // unable to map error response, throwing generic error
                    }
                    Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
                    future.completeExceptionally(new PolytomicApiException(
                            "Error with status code " + response.code(), response.code(), errorBody, response));
                    return;
                } catch (IOException e) {
                    future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
                }
            }

            @Override
            public void onFailure(@NotNull Call call, @NotNull IOException e) {
                future.completeExceptionally(new PolytomicException("Network error executing HTTP request", e));
            }
        });
        return future;
    }
}
