/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.modelsync.executions;

import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.IdempotentRequestOptions;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.resources.modelsync.executions.requests.ExecutionsGetConsoleLogsRequest;
import com.polytomic.api.resources.modelsync.executions.requests.ExecutionsListRequest;
import com.polytomic.api.types.CancelSyncExecutionResponseEnvelope;
import com.polytomic.api.types.ExecutionConsoleLogsResponseEnvelope;
import com.polytomic.api.types.ExecutionLogType;
import com.polytomic.api.types.ExecutionLogsResponseEnvelope;
import com.polytomic.api.types.GetExecutionResponseEnvelope;
import com.polytomic.api.types.ListExecutionResponseEnvelope;

public class ExecutionsClient {
    protected final ClientOptions clientOptions;

    private final RawExecutionsClient rawClient;

    public ExecutionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawExecutionsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawExecutionsClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Lists executions for a model sync.
     * <p>Results are ordered by start time descending. If more results are available, the
     * response includes <code>pagination.next_page_token</code>; pass that token back unchanged
     * to continue paging.</p>
     * <p>The token is opaque. Do not construct or edit it yourself.</p>
     * <p>For full details about a specific execution — including record counts and error
     * summaries — use
     * <a href="../../../../api-reference/model-sync/executions/get"><code>GET /api/syncs/{sync_id}/executions/{id}</code></a>.</p>
     */
    public ListExecutionResponseEnvelope list(String syncId) {
        return this.rawClient.list(syncId).body();
    }

    /**
     * Lists executions for a model sync.
     * <p>Results are ordered by start time descending. If more results are available, the
     * response includes <code>pagination.next_page_token</code>; pass that token back unchanged
     * to continue paging.</p>
     * <p>The token is opaque. Do not construct or edit it yourself.</p>
     * <p>For full details about a specific execution — including record counts and error
     * summaries — use
     * <a href="../../../../api-reference/model-sync/executions/get"><code>GET /api/syncs/{sync_id}/executions/{id}</code></a>.</p>
     */
    public ListExecutionResponseEnvelope list(String syncId, RequestOptions requestOptions) {
        return this.rawClient.list(syncId, requestOptions).body();
    }

    /**
     * Lists executions for a model sync.
     * <p>Results are ordered by start time descending. If more results are available, the
     * response includes <code>pagination.next_page_token</code>; pass that token back unchanged
     * to continue paging.</p>
     * <p>The token is opaque. Do not construct or edit it yourself.</p>
     * <p>For full details about a specific execution — including record counts and error
     * summaries — use
     * <a href="../../../../api-reference/model-sync/executions/get"><code>GET /api/syncs/{sync_id}/executions/{id}</code></a>.</p>
     */
    public ListExecutionResponseEnvelope list(String syncId, ExecutionsListRequest request) {
        return this.rawClient.list(syncId, request).body();
    }

    /**
     * Lists executions for a model sync.
     * <p>Results are ordered by start time descending. If more results are available, the
     * response includes <code>pagination.next_page_token</code>; pass that token back unchanged
     * to continue paging.</p>
     * <p>The token is opaque. Do not construct or edit it yourself.</p>
     * <p>For full details about a specific execution — including record counts and error
     * summaries — use
     * <a href="../../../../api-reference/model-sync/executions/get"><code>GET /api/syncs/{sync_id}/executions/{id}</code></a>.</p>
     */
    public ListExecutionResponseEnvelope list(
            String syncId, ExecutionsListRequest request, RequestOptions requestOptions) {
        return this.rawClient.list(syncId, request, requestOptions).body();
    }

    /**
     * Returns a single model sync execution.
     * <p>For the log files produced by this execution, use
     * <a href="../../../../../api-reference/model-sync/executions/get-log-urls"><code>GET /api/syncs/{sync_id}/executions/{id}/{type}</code></a> to retrieve
     * signed URLs grouped by log category.</p>
     */
    public GetExecutionResponseEnvelope get(String syncId, String id) {
        return this.rawClient.get(syncId, id).body();
    }

    /**
     * Returns a single model sync execution.
     * <p>For the log files produced by this execution, use
     * <a href="../../../../../api-reference/model-sync/executions/get-log-urls"><code>GET /api/syncs/{sync_id}/executions/{id}/{type}</code></a> to retrieve
     * signed URLs grouped by log category.</p>
     */
    public GetExecutionResponseEnvelope get(String syncId, String id, RequestOptions requestOptions) {
        return this.rawClient.get(syncId, id, requestOptions).body();
    }

    /**
     * Requests cancellation of a model sync execution.
     */
    public CancelSyncExecutionResponseEnvelope cancel(String syncId, String id) {
        return this.rawClient.cancel(syncId, id).body();
    }

    /**
     * Requests cancellation of a model sync execution.
     */
    public CancelSyncExecutionResponseEnvelope cancel(
            String syncId, String id, IdempotentRequestOptions requestOptions) {
        return this.rawClient.cancel(syncId, id, requestOptions).body();
    }

    /**
     * Fetch the latest console log entries for a sync execution. Returns at most the most recent 50 entries retained in Redis.
     */
    public ExecutionConsoleLogsResponseEnvelope getConsoleLogs(String syncId, String id) {
        return this.rawClient.getConsoleLogs(syncId, id).body();
    }

    /**
     * Fetch the latest console log entries for a sync execution. Returns at most the most recent 50 entries retained in Redis.
     */
    public ExecutionConsoleLogsResponseEnvelope getConsoleLogs(
            String syncId, String id, RequestOptions requestOptions) {
        return this.rawClient.getConsoleLogs(syncId, id, requestOptions).body();
    }

    /**
     * Fetch the latest console log entries for a sync execution. Returns at most the most recent 50 entries retained in Redis.
     */
    public ExecutionConsoleLogsResponseEnvelope getConsoleLogs(
            String syncId, String id, ExecutionsGetConsoleLogsRequest request) {
        return this.rawClient.getConsoleLogs(syncId, id, request).body();
    }

    /**
     * Fetch the latest console log entries for a sync execution. Returns at most the most recent 50 entries retained in Redis.
     */
    public ExecutionConsoleLogsResponseEnvelope getConsoleLogs(
            String syncId, String id, ExecutionsGetConsoleLogsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getConsoleLogs(syncId, id, request, requestOptions)
                .body();
    }

    /**
     * Returns signed URLs for every log file of a given type on a model sync execution.
     * <p><code>{type}</code> identifies the log category, such as <code>errors</code> or <code>warnings</code>. The
     * response contains a signed URL for each log file in that category.</p>
     * <blockquote>
     * <p>🚧 Signed URLs expire after a short period. If a URL has expired, re-request
     * it from this endpoint. To fetch a single file's URL directly, use
     * <a href="../../../../../../api-reference/model-sync/executions/get-logs"><code>GET /api/syncs/{sync_id}/executions/{id}/{type}/{filename}</code></a>.</p>
     * </blockquote>
     */
    public ExecutionLogsResponseEnvelope getLogUrls(String syncId, String id, ExecutionLogType type) {
        return this.rawClient.getLogUrls(syncId, id, type).body();
    }

    /**
     * Returns signed URLs for every log file of a given type on a model sync execution.
     * <p><code>{type}</code> identifies the log category, such as <code>errors</code> or <code>warnings</code>. The
     * response contains a signed URL for each log file in that category.</p>
     * <blockquote>
     * <p>🚧 Signed URLs expire after a short period. If a URL has expired, re-request
     * it from this endpoint. To fetch a single file's URL directly, use
     * <a href="../../../../../../api-reference/model-sync/executions/get-logs"><code>GET /api/syncs/{sync_id}/executions/{id}/{type}/{filename}</code></a>.</p>
     * </blockquote>
     */
    public ExecutionLogsResponseEnvelope getLogUrls(
            String syncId, String id, ExecutionLogType type, RequestOptions requestOptions) {
        return this.rawClient.getLogUrls(syncId, id, type, requestOptions).body();
    }

    /**
     * Returns a signed URL for a specific log file produced by a model sync execution.
     * <p>The URL is signed and expires after a short period. If it has expired before
     * you download the file, call this endpoint again to obtain a fresh URL.</p>
     */
    public void getLogs(String syncId, String id, ExecutionLogType type, String filename) {
        this.rawClient.getLogs(syncId, id, type, filename).body();
    }

    /**
     * Returns a signed URL for a specific log file produced by a model sync execution.
     * <p>The URL is signed and expires after a short period. If it has expired before
     * you download the file, call this endpoint again to obtain a fresh URL.</p>
     */
    public void getLogs(
            String syncId, String id, ExecutionLogType type, String filename, RequestOptions requestOptions) {
        this.rawClient.getLogs(syncId, id, type, filename, requestOptions).body();
    }
}
