/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.modelsync.errorhandling;

import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.IdempotentRequestOptions;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.resources.modelsync.errorhandling.requests.UpdateSyncErrorHandlingRequest;
import com.polytomic.api.types.SyncErrorHandlingEnvelope;

public class ErrorHandlingClient {
    protected final ClientOptions clientOptions;

    private final RawErrorHandlingClient rawClient;

    public ErrorHandlingClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawErrorHandlingClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawErrorHandlingClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Returns the error handling settings for a model sync.
     */
    public SyncErrorHandlingEnvelope get(String id) {
        return this.rawClient.get(id).body();
    }

    /**
     * Returns the error handling settings for a model sync.
     */
    public SyncErrorHandlingEnvelope get(String id, RequestOptions requestOptions) {
        return this.rawClient.get(id, requestOptions).body();
    }

    /**
     * Updates the error handling settings for a model sync.
     */
    public SyncErrorHandlingEnvelope update(String id) {
        return this.rawClient.update(id).body();
    }

    /**
     * Updates the error handling settings for a model sync.
     */
    public SyncErrorHandlingEnvelope update(String id, IdempotentRequestOptions requestOptions) {
        return this.rawClient.update(id, requestOptions).body();
    }

    /**
     * Updates the error handling settings for a model sync.
     */
    public SyncErrorHandlingEnvelope update(String id, UpdateSyncErrorHandlingRequest request) {
        return this.rawClient.update(id, request).body();
    }

    /**
     * Updates the error handling settings for a model sync.
     */
    public SyncErrorHandlingEnvelope update(
            String id, UpdateSyncErrorHandlingRequest request, IdempotentRequestOptions requestOptions) {
        return this.rawClient.update(id, request, requestOptions).body();
    }
}
