/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.connections.sharedconnections;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.IdempotentRequestOptions;
import com.polytomic.api.core.MediaTypes;
import com.polytomic.api.core.ObjectMappers;
import com.polytomic.api.core.PolytomicApiException;
import com.polytomic.api.core.PolytomicException;
import com.polytomic.api.core.PolytomicHttpResponse;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.errors.ForbiddenError;
import com.polytomic.api.errors.InternalServerError;
import com.polytomic.api.errors.NotFoundError;
import com.polytomic.api.errors.UnprocessableEntityError;
import com.polytomic.api.resources.connections.sharedconnections.requests.PartnerCreateSharedConnectionRequestSchema;
import com.polytomic.api.types.ApiError;
import com.polytomic.api.types.ConnectionListResponseEnvelope;
import com.polytomic.api.types.CreateSharedConnectionResponseEnvelope;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawSharedConnectionsClient {
    protected final ClientOptions clientOptions;

    public RawSharedConnectionsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    /**
     * Lists shared copies of a connection that the caller's organization owns.
     * <p>The returned connections are the child copies, not the parent connection
     * itself. This is useful when a partner workflow needs to confirm which
     * downstream organizations have already received a shared copy.</p>
     * <p>Creating a new shared copy is a separate operation. Use
     * <a href="../../../../api-reference/connections/create-shared-connection"><code>POST /api/organizations/{org_id}/connections/{connection_id}/share</code></a>
     * for the v5 partner-scoped flow.</p>
     */
    public PolytomicHttpResponse<ConnectionListResponseEnvelope> listSharedConnections(String id) {
        return listSharedConnections(id, null);
    }

    /**
     * Lists shared copies of a connection that the caller's organization owns.
     * <p>The returned connections are the child copies, not the parent connection
     * itself. This is useful when a partner workflow needs to confirm which
     * downstream organizations have already received a shared copy.</p>
     * <p>Creating a new shared copy is a separate operation. Use
     * <a href="../../../../api-reference/connections/create-shared-connection"><code>POST /api/organizations/{org_id}/connections/{connection_id}/share</code></a>
     * for the v5 partner-scoped flow.</p>
     */
    public PolytomicHttpResponse<ConnectionListResponseEnvelope> listSharedConnections(
            String id, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(id)
                .addPathSegments("shared");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PolytomicHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ConnectionListResponseEnvelope.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PolytomicApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PolytomicException("Network error executing HTTP request", e);
        }
    }

    /**
     * Lists shared copies of a connection owned by a specific organization in the partner account.
     * <p>The <code>org_id</code> must match the organization that owns the parent connection. If it
     * does not, the endpoint returns <code>404</code> rather than exposing information about the
     * parent connection.</p>
     * <p>This endpoint is useful in partner workflows where the parent connection is in
     * the partner owner organization and the caller needs to audit which child
     * organizations already have a shared copy.</p>
     */
    public PolytomicHttpResponse<ConnectionListResponseEnvelope> listSharedConnectionsForPartner(
            String orgId, String connectionId) {
        return listSharedConnectionsForPartner(orgId, connectionId, null);
    }

    /**
     * Lists shared copies of a connection owned by a specific organization in the partner account.
     * <p>The <code>org_id</code> must match the organization that owns the parent connection. If it
     * does not, the endpoint returns <code>404</code> rather than exposing information about the
     * parent connection.</p>
     * <p>This endpoint is useful in partner workflows where the parent connection is in
     * the partner owner organization and the caller needs to audit which child
     * organizations already have a shared copy.</p>
     */
    public PolytomicHttpResponse<ConnectionListResponseEnvelope> listSharedConnectionsForPartner(
            String orgId, String connectionId, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/organizations")
                .addPathSegment(orgId)
                .addPathSegments("connections")
                .addPathSegment(connectionId)
                .addPathSegments("shared");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PolytomicHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ConnectionListResponseEnvelope.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 422:
                        throw new UnprocessableEntityError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PolytomicApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PolytomicException("Network error executing HTTP request", e);
        }
    }

    /**
     * Shares a connection with another organization in the caller's partner account.
     */
    public PolytomicHttpResponse<CreateSharedConnectionResponseEnvelope> createSharedConnection(
            String orgId, String connectionId, PartnerCreateSharedConnectionRequestSchema request) {
        return createSharedConnection(orgId, connectionId, request, null);
    }

    /**
     * Shares a connection with another organization in the caller's partner account.
     */
    public PolytomicHttpResponse<CreateSharedConnectionResponseEnvelope> createSharedConnection(
            String orgId,
            String connectionId,
            PartnerCreateSharedConnectionRequestSchema request,
            IdempotentRequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/organizations")
                .addPathSegment(orgId)
                .addPathSegments("connections")
                .addPathSegment(connectionId)
                .addPathSegments("shared");
        if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
            });
        }
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (JsonProcessingException e) {
            throw new PolytomicException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl.build())
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .addHeader("Accept", "application/json")
                .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
                return new PolytomicHttpResponse<>(
                        ObjectMappers.JSON_MAPPER.readValue(
                                responseBodyString, CreateSharedConnectionResponseEnvelope.class),
                        response);
            }
            try {
                switch (response.code()) {
                    case 403:
                        throw new ForbiddenError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 404:
                        throw new NotFoundError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                    case 500:
                        throw new InternalServerError(
                                ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ApiError.class), response);
                }
            } catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new PolytomicApiException(
                    "Error with status code " + response.code(), response.code(), errorBody, response);
        } catch (IOException e) {
            throw new PolytomicException("Network error executing HTTP request", e);
        }
    }
}
