/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.errors;

import com.polytomic.api.core.PolytomicApiException;
import com.polytomic.api.types.ApiError;
import okhttp3.Response;

public final class ServiceUnavailableError extends PolytomicApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ApiError body;

    public ServiceUnavailableError(ApiError body) {
        super("ServiceUnavailableError", 503, body);
        this.body = body;
    }

    public ServiceUnavailableError(ApiError body, Response rawResponse) {
        super("ServiceUnavailableError", 503, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ApiError body() {
        return this.body;
    }
}
