/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.schemas;

import com.polytomic.api.core.ApiError;
import com.polytomic.api.core.ClientOptions;
import com.polytomic.api.core.MediaTypes;
import com.polytomic.api.core.ObjectMappers;
import com.polytomic.api.core.RequestOptions;
import com.polytomic.api.resources.schemas.requests.SchemasDeleteFieldRequest;
import com.polytomic.api.resources.schemas.requests.SchemasGetRecordsRequest;
import com.polytomic.api.resources.schemas.requests.SchemasGetRequest;
import com.polytomic.api.resources.schemas.requests.SchemasGetStatusRequest;
import com.polytomic.api.resources.schemas.requests.SchemasRefreshRequest;
import com.polytomic.api.resources.schemas.requests.SchemasResetPrimaryKeysRequest;
import com.polytomic.api.resources.schemas.requests.SetPrimaryKeysRequest;
import com.polytomic.api.resources.schemas.requests.UpsertSchemaFieldRequest;
import com.polytomic.api.types.BulkSyncSourceSchemaEnvelope;
import com.polytomic.api.types.BulkSyncSourceStatusEnvelope;
import com.polytomic.api.types.SchemaRecordsResponseEnvelope;
import java.io.IOException;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class SchemasClient {
    protected final ClientOptions clientOptions;

    public SchemasClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
    }

    public void upsertField(String connectionId, String schemaId) {
        upsertField(connectionId, schemaId, UpsertSchemaFieldRequest.builder().build());
    }

    public void upsertField(String connectionId, String schemaId, UpsertSchemaFieldRequest request) {
        upsertField(connectionId, schemaId, request, null);
    }

    public void upsertField(
            String connectionId, String schemaId, UpsertSchemaFieldRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(connectionId)
                .addPathSegments("schemas")
                .addPathSegment(schemaId)
                .addPathSegments("fields")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("POST", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return;
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public void deleteField(String connectionId, String schemaId, String fieldId) {
        deleteField(
                connectionId,
                schemaId,
                fieldId,
                SchemasDeleteFieldRequest.builder().build());
    }

    public void deleteField(String connectionId, String schemaId, String fieldId, SchemasDeleteFieldRequest request) {
        deleteField(connectionId, schemaId, fieldId, request, null);
    }

    public void deleteField(
            String connectionId,
            String schemaId,
            String fieldId,
            SchemasDeleteFieldRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(connectionId)
                .addPathSegments("schemas")
                .addPathSegment(schemaId)
                .addPathSegments("fields")
                .addPathSegment(fieldId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return;
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public void setPrimaryKeys(String connectionId, String schemaId) {
        setPrimaryKeys(connectionId, schemaId, SetPrimaryKeysRequest.builder().build());
    }

    public void setPrimaryKeys(String connectionId, String schemaId, SetPrimaryKeysRequest request) {
        setPrimaryKeys(connectionId, schemaId, request, null);
    }

    public void setPrimaryKeys(
            String connectionId, String schemaId, SetPrimaryKeysRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(connectionId)
                .addPathSegments("schemas")
                .addPathSegment(schemaId)
                .addPathSegments("primary_keys")
                .build();
        RequestBody body;
        try {
            body = RequestBody.create(
                    ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
        Request okhttpRequest = new Request.Builder()
                .url(httpUrl)
                .method("PUT", body)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json")
                .build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return;
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Delete all primary key overrides for a schema. After this call the schema will use the primary keys detected from the source connection, if any.
     */
    public void resetPrimaryKeys(String connectionId, String schemaId) {
        resetPrimaryKeys(
                connectionId, schemaId, SchemasResetPrimaryKeysRequest.builder().build());
    }

    /**
     * Delete all primary key overrides for a schema. After this call the schema will use the primary keys detected from the source connection, if any.
     */
    public void resetPrimaryKeys(String connectionId, String schemaId, SchemasResetPrimaryKeysRequest request) {
        resetPrimaryKeys(connectionId, schemaId, request, null);
    }

    /**
     * Delete all primary key overrides for a schema. After this call the schema will use the primary keys detected from the source connection, if any.
     */
    public void resetPrimaryKeys(
            String connectionId,
            String schemaId,
            SchemasResetPrimaryKeysRequest request,
            RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(connectionId)
                .addPathSegments("schemas")
                .addPathSegment(schemaId)
                .addPathSegments("primary_keys")
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("DELETE", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return;
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public void refresh(String id) {
        refresh(id, SchemasRefreshRequest.builder().build());
    }

    public void refresh(String id, SchemasRefreshRequest request) {
        refresh(id, request, null);
    }

    public void refresh(String id, SchemasRefreshRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(id)
                .addPathSegments("schemas/refresh")
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("POST", RequestBody.create("", null))
                .headers(Headers.of(clientOptions.headers(requestOptions)));
        Request okhttpRequest = _requestBuilder.build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return;
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    /**
     * Polytomic periodically inspects the schemas for connections to discover new fields and update metadata. This endpoint returns the current inspection status.
     */
    public BulkSyncSourceStatusEnvelope getStatus(String id) {
        return getStatus(id, SchemasGetStatusRequest.builder().build());
    }

    /**
     * Polytomic periodically inspects the schemas for connections to discover new fields and update metadata. This endpoint returns the current inspection status.
     */
    public BulkSyncSourceStatusEnvelope getStatus(String id, SchemasGetStatusRequest request) {
        return getStatus(id, request, null);
    }

    /**
     * Polytomic periodically inspects the schemas for connections to discover new fields and update metadata. This endpoint returns the current inspection status.
     */
    public BulkSyncSourceStatusEnvelope getStatus(
            String id, SchemasGetStatusRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(id)
                .addPathSegments("schemas/status")
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), BulkSyncSourceStatusEnvelope.class);
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public BulkSyncSourceSchemaEnvelope get(String id, String schemaId) {
        return get(id, schemaId, SchemasGetRequest.builder().build());
    }

    public BulkSyncSourceSchemaEnvelope get(String id, String schemaId, SchemasGetRequest request) {
        return get(id, schemaId, request, null);
    }

    public BulkSyncSourceSchemaEnvelope get(
            String id, String schemaId, SchemasGetRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(id)
                .addPathSegments("schemas")
                .addPathSegment(schemaId)
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), BulkSyncSourceSchemaEnvelope.class);
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }

    public SchemaRecordsResponseEnvelope getRecords(String id, String schemaId) {
        return getRecords(id, schemaId, SchemasGetRecordsRequest.builder().build());
    }

    public SchemaRecordsResponseEnvelope getRecords(String id, String schemaId, SchemasGetRecordsRequest request) {
        return getRecords(id, schemaId, request, null);
    }

    public SchemaRecordsResponseEnvelope getRecords(
            String id, String schemaId, SchemasGetRecordsRequest request, RequestOptions requestOptions) {
        HttpUrl httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl())
                .newBuilder()
                .addPathSegments("api/connections")
                .addPathSegment(id)
                .addPathSegments("schemas")
                .addPathSegment(schemaId)
                .addPathSegments("records")
                .build();
        Request.Builder _requestBuilder = new Request.Builder()
                .url(httpUrl)
                .method("GET", null)
                .headers(Headers.of(clientOptions.headers(requestOptions)))
                .addHeader("Content-Type", "application/json");
        Request okhttpRequest = _requestBuilder.build();
        try {
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
                client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            Response response = client.newCall(okhttpRequest).execute();
            ResponseBody responseBody = response.body();
            if (response.isSuccessful()) {
                return ObjectMappers.JSON_MAPPER.readValue(responseBody.string(), SchemaRecordsResponseEnvelope.class);
            }
            throw new ApiError(
                    response.code(),
                    ObjectMappers.JSON_MAPPER.readValue(
                            responseBody != null ? responseBody.string() : "{}", Object.class));
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
