/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.temporarycredentials.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import com.polytomic.api.types.TemporaryCredentialSubject;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateTemporaryCredentialRequest.Builder.class)
public final class CreateTemporaryCredentialRequest {
    private final Optional<Integer> durationSeconds;

    private final Optional<String> sessionName;

    private final TemporaryCredentialSubject subject;

    private final Map<String, Object> additionalProperties;

    private CreateTemporaryCredentialRequest(
            Optional<Integer> durationSeconds,
            Optional<String> sessionName,
            TemporaryCredentialSubject subject,
            Map<String, Object> additionalProperties) {
        this.durationSeconds = durationSeconds;
        this.sessionName = sessionName;
        this.subject = subject;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Credential lifetime in seconds. Defaults to 3600 (1 hour); minimum 600 and maximum 14400.
     */
    @JsonProperty("duration_seconds")
    public Optional<Integer> getDurationSeconds() {
        return durationSeconds;
    }

    /**
     * @return Optional audit correlation label, limited to 128 characters. Do not include secrets or personal data.
     */
    @JsonProperty("session_name")
    public Optional<String> getSessionName() {
        return sessionName;
    }

    @JsonProperty("subject")
    public TemporaryCredentialSubject getSubject() {
        return subject;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateTemporaryCredentialRequest && equalTo((CreateTemporaryCredentialRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateTemporaryCredentialRequest other) {
        return durationSeconds.equals(other.durationSeconds)
                && sessionName.equals(other.sessionName)
                && subject.equals(other.subject);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.durationSeconds, this.sessionName, this.subject);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static SubjectStage builder() {
        return new Builder();
    }

    public interface SubjectStage {
        _FinalStage subject(@NotNull TemporaryCredentialSubject subject);

        Builder from(CreateTemporaryCredentialRequest other);
    }

    public interface _FinalStage {
        CreateTemporaryCredentialRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Credential lifetime in seconds. Defaults to 3600 (1 hour); minimum 600 and maximum 14400.</p>
         */
        _FinalStage durationSeconds(Optional<Integer> durationSeconds);

        _FinalStage durationSeconds(Integer durationSeconds);

        /**
         * <p>Optional audit correlation label, limited to 128 characters. Do not include secrets or personal data.</p>
         */
        _FinalStage sessionName(Optional<String> sessionName);

        _FinalStage sessionName(String sessionName);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements SubjectStage, _FinalStage {
        private TemporaryCredentialSubject subject;

        private Optional<String> sessionName = Optional.empty();

        private Optional<Integer> durationSeconds = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(CreateTemporaryCredentialRequest other) {
            durationSeconds(other.getDurationSeconds());
            sessionName(other.getSessionName());
            subject(other.getSubject());
            return this;
        }

        @java.lang.Override
        @JsonSetter("subject")
        public _FinalStage subject(@NotNull TemporaryCredentialSubject subject) {
            this.subject = subject;
            return this;
        }

        /**
         * <p>Optional audit correlation label, limited to 128 characters. Do not include secrets or personal data.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage sessionName(String sessionName) {
            this.sessionName = Optional.ofNullable(sessionName);
            return this;
        }

        /**
         * <p>Optional audit correlation label, limited to 128 characters. Do not include secrets or personal data.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "session_name", nulls = Nulls.SKIP)
        public _FinalStage sessionName(Optional<String> sessionName) {
            this.sessionName = sessionName;
            return this;
        }

        /**
         * <p>Credential lifetime in seconds. Defaults to 3600 (1 hour); minimum 600 and maximum 14400.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage durationSeconds(Integer durationSeconds) {
            this.durationSeconds = Optional.ofNullable(durationSeconds);
            return this;
        }

        /**
         * <p>Credential lifetime in seconds. Defaults to 3600 (1 hour); minimum 600 and maximum 14400.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "duration_seconds", nulls = Nulls.SKIP)
        public _FinalStage durationSeconds(Optional<Integer> durationSeconds) {
            this.durationSeconds = durationSeconds;
            return this;
        }

        @java.lang.Override
        public CreateTemporaryCredentialRequest build() {
            return new CreateTemporaryCredentialRequest(durationSeconds, sessionName, subject, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
