/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.polytomic.api.resources.bulksync.errorhandling.requests;

import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.polytomic.api.core.ObjectMappers;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = UpdateBulkSyncErrorHandlingRequest.Builder.class)
public final class UpdateBulkSyncErrorHandlingRequest {
    private final Optional<List<String>> subscribers;

    private final Map<String, Object> additionalProperties;

    private UpdateBulkSyncErrorHandlingRequest(
            Optional<List<String>> subscribers, Map<String, Object> additionalProperties) {
        this.subscribers = subscribers;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Email addresses notified when this sync fails. Replaces the current list; pass an empty list to unsubscribe everyone. Omit to leave the list unchanged.
     */
    @JsonProperty("subscribers")
    public Optional<List<String>> getSubscribers() {
        return subscribers;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof UpdateBulkSyncErrorHandlingRequest
                && equalTo((UpdateBulkSyncErrorHandlingRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(UpdateBulkSyncErrorHandlingRequest other) {
        return subscribers.equals(other.subscribers);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.subscribers);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> subscribers = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(UpdateBulkSyncErrorHandlingRequest other) {
            subscribers(other.getSubscribers());
            return this;
        }

        /**
         * <p>Email addresses notified when this sync fails. Replaces the current list; pass an empty list to unsubscribe everyone. Omit to leave the list unchanged.</p>
         */
        @JsonSetter(value = "subscribers", nulls = Nulls.SKIP)
        public Builder subscribers(Optional<List<String>> subscribers) {
            this.subscribers = subscribers;
            return this;
        }

        public Builder subscribers(List<String> subscribers) {
            this.subscribers = Optional.ofNullable(subscribers);
            return this;
        }

        public UpdateBulkSyncErrorHandlingRequest build() {
            return new UpdateBulkSyncErrorHandlingRequest(subscribers, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
